apiVersion: v1
kind: ConfigMap
metadata:
  name: satellite-data-publisher
  namespace: satellite-data-dev
data:
  publisher.json: "{\n  \"environment\": \"dev\",\n  \"root\": \"/data/dev\",\n  \"\
    app\": \"/app/SatelliteDataApi.dll\",\n  \"dotnet\": \"/usr/share/dotnet/dotnet\"\
    ,\n  \"credentials\": \"/run/secrets/s3/credentials.json\",\n  \"bootstrap_database\"\
    : \"/data/dev/bootstrap/baseline.db\",\n  \"allow_production_publish\": false,\n\
    \  \"storage\": {\n    \"bucket\": \"cosmotrak-data-dev\",\n    \"region\": \"\
    us-east-1\",\n    \"prefix\": \"Satellite_Database/\"\n  }\n}"
