apiVersion: v1
kind: Secret
metadata:
    name: satellite-data-r2
    namespace: satellite-data-dev
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:+7EFtUlNXZsScDofi4/EYEvaovK4RdV93uiv5vF0J9blGamBRx7Jwu8JfMSdKi4tMsANVcJBth7C8yYy72+oGid+fI9rUIC1UvNiEjV7vqeg9TaOQFS0CgtOw2Psh6UmfsmmAPAhJqyzXD2HzrF0rY4IyaG49rGT5aBNMKCMRmTh4DS+lZLuupPY,iv:LCdSD0Wi4bnG6QMLGW9xUJz3MNQM5BPS2/xFDAYn7ZI=,tag:KCRzMTSY0SevO6l66t2N3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMXluQTNRVVIzaDRPQ0RR
            NDJ6aTQ0U0l0QnhMWjFyaVo0LzBvOE85V0ZFCnhobi9QakNWWVlqWGdpSnVwNnBU
            N01oc1VKa05VZXJUM3dkYXZGdEk2TG8KLS0tIFdyaW81UU5JdGdyOHFOMW9rR3c0
            a0RmanZiTG5yZDE4OUtRb1V6RlR4N00KtR56MQJpp+611DLoOPI32WEcz0DNUPob
            r0a8mwpsctElA7urWeBJP+49vpE1Nu188lhJTjZQ/q4N5qK4u/Sg1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T05:06:12Z"
    mac: ENC[AES256_GCM,data:10/t3M9uv4VsxhuYIBfERrmNCvBCCDF5FeeHN0oxOjdk4qQJ+sW8yDJegGY6Zx2Bbywb3jp3xV3jdyUtNBvr+eiLh2SiexOFBgLiV849/KVka/DwUV9otqiokh/iqUVdsVp7ZXYursYCbdZDBIBBsWlp9WUmlwxFhVHjHtbAUXA=,iv:drGWre3pKJNAQHaz0hdVhE2H4V6qP1e2Tkw57dOaXiM=,tag:xXaFBm0HIjdnzV0u9vNdCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
