apiVersion: v1
kind: Secret
metadata:
    name: satellite-data-registry
    namespace: satellite-data-dev
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:W4i6Z756Dk77dHsbLQcaxHSz5vq3ygQQfbZMN2CirZVClYE7UJ+3RsB2ThrZgIHg16Xt1U+AUtUdXvnDbqN7apdX7HhxYnC9n9CHiFP7TYgnTJpzur8iezkds5P8r3uHJ2mgGPiyHaz7atu29ESBrEMgN8Rnd4DEr2TB51gmUZ7kOFjtJwptTG30WPgjGH+cQQnqJxL/9kWMxi8gZdXI24fl3FSb3TWngh+68T/m6symNVjQnHkIeQ==,iv:JM6bPs4iX6p7nBpjWuiNIaj1wFkETZ5O9Aa30ahN4c4=,tag:jgzg35bH7PKGNamDMxttkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVC81VWRGN1BobWhHVTVB
            enEwd3FGVjROMDNYNzFVMWY1TzNKT3RJSldRCkd0THl2UzdQL282b2pMSDFWN3pF
            TlYwWE5PeExrNjVkZ0Nqd3lLb3llTzQKLS0tIDdlRTlIOC9WMzcxaEtQT01SZWtn
            U2ZxNDRGdkpJSnVRcFIxUEYrbzBBYzgKyciqHo2C0IQ+16AcYxu7L50Oi8hGuv0g
            lNw6PiMMhENTbXUhDkgyULI4Uzvh7YLuXBPalvIpx+5RGods7X//Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T05:58:40Z"
    mac: ENC[AES256_GCM,data:r2e1SHDtYljI/Kab/V8F9ybGi+71kdlPa+wwk+uj5AR/butAsvaGu/wtxu+J4I/hF9erft8EywnOKxQ6czgZlKKSEhHLHvAqqqXvZCtx7X0Y9WgctDhO9EKAPzIeDy9bUtxxEDXrE9xOQAlCu5pl8JxJ69lK/fgrmpypJnr5HhI=,iv:35zsmldJ2j9eZowiGVhWQNF7eAT0xhZZWKWT0XwH2ys=,tag:z5+cFDc3fvPp1Na98SmgqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
