apiVersion: v1
kind: Secret
metadata:
    name: satellite-data-s3
    namespace: satellite-data-dev
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:ek50TJW31xj6ficwtt/wHuj9ohO9RK14X4mNbemkpgEOF0wzW8LZQ5GyIlkd35fc0l9rbaX5uygKSWs9AhmKhm6eek4rdnkGp/HMNyEcwOvB3ziGNJ2JWZtXPBoUHFF3u2QwRzlP,iv:JL5oL7J3unXgEsVjJP14rFV+HB5ToDGtMWaKoy1ZzFA=,tag:y0ZSR0Ob0t4cX4Om7BqqNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb2t6ZW1tYnBoVUtXbXlU
            MnhaRnV3eW9xMktRcXFNMVY4MUlrQUFIbmc4CldVaUJOYW12dm56ZnI4QlFmVVNJ
            dkdIejdoNTJFRStmUG4rMUNDREFTdTQKLS0tIHhLanFkY0ZnYW1FVEFsWGlZZ0dl
            TnpuZzZ0R1B6WDV2S3d2TFgrODBJK0EK38rGvPHv347T+K7s4Eq/3nz9Evu+mpby
            2CxrpnFQVHeVEd2KaTzuze3c4lFbU9MstTXmx+5ppVUXZQD3MqTugw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T05:57:09Z"
    mac: ENC[AES256_GCM,data:/m8gDtz7w9m8k5VDb2ROo8ktRHDk0vVhOZiZdcr8SbFNYdioYx2oO8Z2J1wB9t9X8OmbSghhHWrL9KMnxd4qYnyaiN8OeDoWDHWAOG4VP30zmGpAgp4qA2n9ExdbPf9dXN8Xjpm3XPgpV2MKtyie72POOr7QOTYtLRFxdpN8VVg=,iv:bx/+Pb5oX2QxTqfe0jgjonKUyiE2NxsKn663BB5Lm0A=,tag:Dpbr4U/rOkeE2cKZ2mKWrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
