apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:aVgjE9U=,iv:2fTjA7KRlEfdmpOgcISHQYejkMtwh0NZ1QyzfzUsFF0=,tag:lNgNn6U4IbXTJlw1QdDuXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0T0lxVS9Yd21ScWVKZDN2
            MS9DQXorUEhjeE42Nm5jSHJaZmlYR0NDeERJCmozcHAzN0RkazlvMkswbklZOVha
            ZkFEZU5kdmxoaW1mU1M0bzNlL09YUmsKLS0tIGt4QllmK1dNQkowVjc2ZGYzQkov
            c0UrczZTRTkrZXEzbzhqclFmYk0yOXMKNg0Yn+GE+kusi4KYEyte9LsuGwQ1REs+
            bnJZjAW8FzkfojeeOx3rtLt5frfNPi94V/Nb+TDgXwjrnOKU5nhjww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T01:57:07Z"
    mac: ENC[AES256_GCM,data:rKFBMnDEkFYPoO/R5LUyw9mpJTMvpCZz5Cfkat1LXSd+98fFcgBpaUfy3TTbm6TyHP0CXgFCQHl6S4+JrFQWcpxJwcL0xgY5IZQzORtO0cL5rI6apbMWgaeP1mKR7BoI766BRMAX7i+a7I0PFzeptu6yBUNRkHnQ2nJR8MqsOt0=,iv:EtrjiysNFHTlfOPKXZ7VfUuHynmqR9Fa84TJoQjn11o=,tag:YeLXUEz+lbYdVW47RFjV2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
