apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-longhorn
  namespace: monitoring
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/olympus-app-backup: enabled
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-resilient
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-longhorn
  namespace: monitoring
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/olympus-app-backup: enabled
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 10Gi
