apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - netbox-secrets.secret.yaml
  - netbox-oidc.secret.yaml
  - database.yaml
  - valkey.yaml
  - access.yaml
configMapGenerator:
  - name: netbox-values
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
