apiVersion: v1
kind: Secret
metadata:
    name: netbox-secrets
    namespace: netbox
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:U7JiIPo=,iv:243L5VzfLcF1C2c9xs9z8Rk1v1/ulQtXMf/dArSmzHg=,tag:tXV30XpquJ651d3uR4vS1w==,type:str]
    password: ENC[AES256_GCM,data:P4GTnSyrd/Y9hbmFmyjrN4EwOiBCeVLD8NF/D1OXz7fbUb4OokKHYqA3yArogAAT,iv:VJcTsOz80FyxkqJAbmjswgHdWy82603Un6faEIDDuOw=,tag:0YgOsQeAIn1L7Wx/Xyl0cg==,type:str]
    email: ENC[AES256_GCM,data:H7t1TEBIClFBDtHmr42xYODvO2k=,iv:QVb4cLoff9b+BbpeTcakl/4FUo32i7Vo/JPStf+Yxls=,tag:73uZLRGQ6xrv7ikLMr1Diw==,type:str]
    api_token: ENC[AES256_GCM,data:nd2fDimRUXnu6JtcPI1KS+g9I6rqqWB6FSLEnKutSbSPj0mqx2hYMQ==,iv:V+njVDWtn4jt8PsUYVN0WHUTIpL9RWABhC4NOgq7suc=,tag:rxoLceCbmIHRCd9lbRwodA==,type:str]
    secret_key: ENC[AES256_GCM,data:hoTkZcHJvbdGm8tsYRD6wfPN7C55lK733HyJ1AuhnWoGmtF+mHF2+9T5FZoZ+D7ze6myCSeznr7E8KnBtVWv57ApiBgK89qYkvaiX+E703Tk4CmK6Zu+4nW8REPKbx2E,iv:qGW5qzZk6R11eMPPUvUg6dWb+VTsQ8+bUb/kzXqMZ2E=,tag:v1YaSPljy6c6Z7iU7RB+pw==,type:str]
    api_token_peppers: ENC[AES256_GCM,data:QZO16CZz1xrv/1KyhKDpRcYNVJ6FE1S2MyuQQeVMHV1wHqsruLM8meKIdBtYflBmUI3NEyxSZQHhD0VdCDY4dxa51975ClRz5uKYv+Qqnu4/Iw9XREQtnRmAhLw+Ovzg9q6AH0KZXjc=,iv:3Dq+49F69KFDnzwEb47pBcniR2OEJd764OBbbdjC874=,tag:ygDg/hFs6jiAgB/zPJp60w==,type:str]
    postgresql-password: ENC[AES256_GCM,data:06DH4GvFVZh+R0saBhtFXANA9kJ6lO+jQwpQ/SpXtIgjeArjDok4QBRzrdtTCbBdwtjwWMVCh/vHD49yQvnl3g==,iv:uYztyxFurg5TdGaX28yBqiSu4jnq8AbDiiiyzuZvnTs=,tag:GVO2Jy3+B20JJNXjV49FdQ==,type:str]
    tasks-password: ENC[AES256_GCM,data:qg42QNRXsevgBnxg/X9WrLVD6z0QU2WL0W2+L4HpGkq6iZkKGVZK114CPqmICcVB5GoSRVofzm8TZZDBkE/esw==,iv:IBha33EK0sFPX2ZAoqpAt8jJC56ebRHjjUKHwLaCF9o=,tag:JH6cesumIT8y/EK002kC4g==,type:str]
    cache-password: ENC[AES256_GCM,data:sWqpZWKxDkSLcxv/84qcMwIPpMyeG1g+xRRoRna7n2EYxpnbTtzOBAblUkElfEQ40XeJGCJNYlCU+xWAl4Tk7A==,iv:2rkY6S/3D43M03rzEM9vkfGq+0Vv47CylimEMjlfDCc=,tag:zqsLPXb3xWL8vTe3PrPFIw==,type:str]
    email-password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYWpucHJDSGp6WU9HR3NS
            cTc3TnVDTDJLL2o1NzBWM3B0OVcrV3Jpb0hvCjc4U0hDelNrSHFydEMvdWF4YkVB
            UlRBODNaTnF6NkFRVXp6ZHBOSlB4eTgKLS0tIENHWXFjS3ExallQMnl5VFVhUlVX
            K2dJTldOYW9YUUlINFY1T2pDem12T00KQWiydJ/GBct3k+iyfswy3W3khKGgMjzZ
            pa5oK3LCI83mWqfpELfjW+TVAdDqvHCs3drODeZPB6iG7ef8oUsE4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T02:28:13Z"
    mac: ENC[AES256_GCM,data:4/F7rQRvQFkI7i/3xmwwyyOJTBRU71xC7dE5WDsx3/fo9Huq0gMeMNZlDSq44KJ34h+w/MIcxb3YHEVqCC4F4v5cBt1CDo9FQYKzEJAEPhfW31yRwvKBpgJc1D2SOSDBQhv7F6gkb5APDf7RJ7A1Owr5uT41sfNDhO9oNVTJZA0=,iv:Sb4D6f4PwGlWLjTvteaLKliRwQcyzFvgvwenjotaL24=,tag:9aOlsCGz90bxjl0kHr9nGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
