apiVersion: v1
kind: Secret
metadata:
    name: netbox-oidc
    namespace: netbox
type: Opaque
stringData:
    oidc.yaml: ENC[AES256_GCM,data:2bCbh5x0NI5Ky2GMHcmFAHSt/EyAP/fBEIx0z7W2rRRIC4mJsUmG0DvH8dSUCWwylYKVCD24hKkeaNLe0VT2+d3UvPtMk5p1WRKto0SdQtaELFfTslwPJgiZzl0A//zEydb6I47lkL6lgy3MfpD86uGy+sy588ieF6L+tsxKSiiIg/M0luVtkP8tYbElS5683fwgf8J21MJzvG7BrC4nubRpEha9k61KUZTP7M6ArQ562C++jWXd/9+IZf4yaIsxsB0zQ4coTWGVwbmrxv1c9az/cCNnVkEcTQG7lpNHnK9PG3L0rBqm7/OGhPuwmcyBG+F2DySZQNp1ZHnUFVusILtD9kQ3UuFA8g==,iv:Fmw5qCZtX6euuBpQvPqxAEo4M9DrZhWrdM0VbLKox98=,tag:j/pLA/TG4jpq3HMg5EBDYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaV2V2bS9wSFROREo1TkQ1
            cmljeXZGWTdIMGFIMlg0MUZjdHdGNGpIc1dRClZ0QXZ2MXowaEFiaVFOSjk3d3VI
            MW5zRGdpWTU2NzJ6MGZLNGIzTDd1bUkKLS0tIHJ2ZEw1ZXFvYUI1OTdyWUFTNDI3
            elRxekhkeGJJbUhraEVCMFNrNVhORGsKhyTO5JuQAwqw2yNjRoHRTaBL4u47rQng
            BwUs2CrdyKpPPqrgQi1yALErY/phS1Q3Rp6DHYu0PFFARIBzANaUDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T02:20:04Z"
    mac: ENC[AES256_GCM,data:0eL9BVWYCTqNjUjskNJdms9NGV5gwZGuRHkU8v5wLWMXL7mbTRhth8HF2E4sIhwCGuxOPrordZwFD7+dy2xoZo6+iW2C3J/ZlfTQRmvb24jyb68oiucsy3FslVueM5TDuvKeqVYQLlfqZ1i0vCZHUd9sGdSZmCwkcAhH2hmmmo0=,iv:iDnQlYsWmzON0Y4tXXTjBbiRVQbitK30OvKHn9eEM5g=,tag:Fl+A2JjR4aqX1x1bkjb7cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
