apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 30m
  timeout: 20m
  chart:
    spec:
      chart: netbox
      version: 8.3.47
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: netbox
        namespace: netbox
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: PersistentVolumeClaim
              name: netbox-media
            patch: |-
              - op: add
                path: /metadata/labels/recurring-job.longhorn.io~1source
                value: enabled
              - op: add
                path: /metadata/labels/recurring-job.longhorn.io~1netbox-media-backup
                value: enabled
  valuesFrom:
    - kind: ConfigMap
      name: netbox-values
      valuesKey: values.yaml
