apiVersion: v1
kind: Secret
metadata:
    name: vpn-egress-credentials
    namespace: vpn-egress
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:DWeelO8XW4ssLnrXghjxffmmT+QPJffv,iv:REpTGTgqDG3nQYt9sej7MkxAMY6rp35hziD0eS2UHKk=,tag:Wh/w9HcJFzxPR4WcT/Cj2g==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:DIdaPo8ZG0NhJxLu2e7TxkPF/YyBcRiP,iv:2Xe0Be9mJIeSzJfHHXq83kC7KkHPVMAQCNYNec7f1RM=,tag:HBquNJpCzRtVNLijx+NtSA==,type:str]
    HTTPPROXY_USER: ENC[AES256_GCM,data:3PkCnkCGhR1tVWw=,iv:FuwItkyH7+oRL2G8VJNQIYsYYOMPR6qJwGX42p2K4NQ=,tag:t+wt+UO8xroLbOJVEqbdsQ==,type:str]
    HTTPPROXY_PASSWORD: ENC[AES256_GCM,data:BiAmVJUY/pAsAD8JwcGNJKs/qi0oMSO0eYyy/Xy20J3XcjcNzQ1jqAOonPnh9Ktt,iv:yfHzTtSc9wvl4+4n26i6qNJk9QkeKEVDVumUCO0xnD0=,tag:bf35/ijIpQRafPkdrQtcgQ==,type:str]
    SHADOWSOCKS_PASSWORD: ENC[AES256_GCM,data:fIYW84V2moHPufITCPHAqAedxQ4EOCIQdUyX98tyQ+0TExS9Rhe4cU0ysY23J+H9,iv:ntChJYoszxbu4U9Fhr3eHQEslqdVHV8VKSoVqL4+Nfw=,tag:rILjWlmhs6cfRSia2KH9Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMmtJUEdFNGpEbVFxRnBF
            TE11bnpIQ1lLb1c4VEVGR3FaQkpINTRBUlVZCk9qckMyeXJ6ZE4zbzVRbXdlK00v
            elp1N2RySXNZSUNCR2RJVFI5Yngzb2MKLS0tIEtXVEpRNExBWnl6S3ZCYkxUVy9y
            NzRILzBDMllTY0QwS2FoZmszNVlCdncKskW/ZtQva/RvLLfGHDPqlNVoLAMpe1Or
            hqDuheB0Kbmbp/ObI8jQ451MUI+rqiHSqS0SB+xa/hwmuYZIdv2osQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T00:06:37Z"
    mac: ENC[AES256_GCM,data:jcv8A4MXgEARmY7PbupksDHH1G0Bz8tbspp5pQ2lOq/SzVrLerefB4lQWBmAH5IuLne1b8o4miRktUoSV+T5DkPS1SEMGP4acSr9FsgixKCDKUBgbb3TJkgvzGqXarjgl7noB5KjMgXftmvRp6gWzJITTy8Ub1H3kQ5EluqPRQ4=,iv:LERo1k2S91F3KsIVGvzkH9/FG1ZEmevp4DC4NIO9ul4=,tag:9NKnkKXhbqAxKaPgtOQzTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
