apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- homepage
- monitoring
- portainer
- pihole
- n8n
- uptime-kuma
- coder
- authentik
- headlamp
- telchar-construct
- telchar-forge
