apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: cosmotrak-notifications
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:sAMSowOvehkst3aK5WUJxyvYjjhbM9DAWKWrt0xQGxp1r0+3WpnxMfZgM1nZ/CqGYnk0/ySPJpuPN1zPk0wkMNpR/MqYR2rJL9PqvcjiQKeLClCnLDhdxmF/4rCVHYhO69Vx63agt5ux2CF6byW7Uds6Kl5P,iv:G23E86cjii1lXbmUMRMZcUwTREfNFxXNP8YOqT92WRg=,tag:KDrXlkocCAXzo+NfMTTQqQ==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:QJe1+7mydmBDrD8OB45EJC38OYseoYoZRaHePP8johB3a17ZfjrGIbsIlOweMq1J8v61iinaI7OFyLQZq4DEqQ==,iv:PWRIdDyXlTPY9Z1H1oFjGHbfnaTUafozx1VNq3M9lkI=,tag:5oQaVU41DL8xyDP1gSsGUQ==,type:str]
    RATE_LIMIT_SECRET: ENC[AES256_GCM,data:y8GGQHTCVQtZNQG1wXdxMnxgkfMZFVt421CiWuWwwNex4QnrmNhk+gkGVRsN5sAKrYJdFLAhqPRAxAsgFTKT0Q==,iv:DCj32gbpT9R71jcyivI0UVaPiOr4FiOQPxZN1ffxR7A=,tag:15DDdzRmnNkPRs6aW4ZbXw==,type:str]
    TOKEN_ENCRYPTION_KEY: ENC[AES256_GCM,data:t+Denmm8v6zWu9Uc7ROO2oKMMMzAaoafpQvyqTq08wnXvEiD+dr2F3NsT4g=,iv:a9bZmyIviuSrHlvfXSVn5glcWGPE6t9XjPxSvV+28rM=,tag:HAwlDvXQ3kQTAEioIqoOzw==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:RwDLIfXs8mO7ZRFPY+r53f+rMVnCHsQ=,iv:PV2XGTZkuITTFaz8YLnnyMsss3EB6T5LniNOMzXGUEY=,tag:yzZIMoOHbWmW01/qZCgYow==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ZCtza9vPOP2mOgM57Akl+ADxpfeHx6KUrHPDKQ/BdXDtvHlNoG/Jcf2p/woms0lvTyJEYbVU6TzpWIG07OrKTg==,iv:4usjEzgw94/2mkslrZEyBwpdg8UwkpJwN6c6/mxfEKE=,tag:YXg/yDUYZGbaJKKrYeMlxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML3hacGV4YmVXZiszV05J
            bzk4ZGlYeVR3U2U1Y2ZwRklUenNDYzhnNWdvCjhvU200dlF5Zis2dHZLYVlaaENt
            aVRjM3JjK1lzbXczNDFmNFNqNVp5bW8KLS0tIFdwZktIOG14Ym5PVmNQUjY1bmdh
            V3lDNUtWejBVWFhESndFMVZILzVZaUEKn+jvjSbmmBGSTjYBoQUnliS+iVG+9iol
            xaJEHhnIb73L7ig9H/Cz6C7EhDiy+2A9cDsPcnYIQ0nirx+rOioPKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T06:03:20Z"
    mac: ENC[AES256_GCM,data:lTOo/E2WRdc6Rq0ZHHHJ67P/OR3o7tszLZuV3NfzTGNzFhqzYtATtAsbDkGuc+ReWMaFFKAwoPNHhqYH6vw1ArlPSDakEkrgBiXM3CRhAYZsiVOwReu5pRv/076CIulDT8a1LOCs11vy0CjUS9YpvFP6nqv3qWstcG26fDF0wpM=,iv:Rvwu2MfyFfykuQ7/Dq7Aa+iylUnY3IACweuD6fSDBWs=,tag:ogPP+pbkgg6ZSiJ3JcYOyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
