apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: cosmotrak-notifications
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:r2fI6grbqUeJDBs2i52McKVwlITEDDRc0mNutjZepTan9W+4QUnsrhoY1IZWAUPL/KQqrGLTOtizZBlc4KdSsF6NPyG7eThCEuLZFI+AFiLZgzxD5JfBo9DnTxT6IiXxoj3pUh4wIfZ8FZr3zZIL4THi91Ab,iv:Bvrgfuy3Eiq7/a6Oe9Ama07PNfgkR3m2Mpom//2HpvI=,tag:6Z3kIGalNwPUM2+BYlZRfA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:nBB0+eRHw8/YCuAFUWaBfhuGD2KEDzjzxBYWUecjqkz76OPMI9fYv4INv3t5FjmbQxDhObkWEefcgCzFrE+N+g==,iv:pD0tS7QUO7LZMC0/WznyLnfb6z91bWiHF4M1xsy6f44=,tag:14lFNLLKm3A8PS0oMd0J1A==,type:str]
    RATE_LIMIT_SECRET: ENC[AES256_GCM,data:CZbWdnTymnPQ+wA9tOubLtSY11q+iPb9dnpF+a3WS3v+yvzS2iP59qdyMnIBOpNuXLQEt1ybAV2U2HCqTUcFxQ==,iv:aRluU7ZgRZrlQgLrChs5WVD6N0ifD5w4pcR+BlvlOWM=,tag:5hSbWlb9gg4ajA50mN6qdg==,type:str]
    TOKEN_ENCRYPTION_KEY: ENC[AES256_GCM,data:KVD+A4ivWBb4F8cHDKMAKe5Ecl/cV96vEj48V4mxzCHpva1PNJ4vjI5TQtA=,iv:7poE85zNtixLj+naLuwBbL24FXEJmQPl+4mCoSdkIOM=,tag:JG+FvsFpd1K7OLRf5gzS7w==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:x+dASKR1gz8qH//0iRsMH96iEwLJO7s=,iv:qYyNlmsKwGyRU9KvRIiKnr48RLgha3KeDfvomb1btoU=,tag:8xpjbBNHmFSww4fa3U+G9Q==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Ny74EF5KPsYvP5dzadQ9k4778HqeqjoG6lRqpbkFE1t59bUfxshUHYpHlbMGAmuha67HUzo2YdY1feVtXRUtGw==,iv:/nX2ivsHv5Ot8yJviZJo9kxyoNPVVn39pjnub5b3E1Y=,tag:T7MMas/+SBFj7o498CYggg==,type:str]
    OIDC_ADMIN_SUBJECT: ENC[AES256_GCM,data:1vSJSLdQTNxoSNZJiKKcMNeqXd98SdUKbcYROGkJrhiXIKiq,iv:zJy8zgkX3K9DKPquWoqsdd6+CWAsNErjPL0R1m6l1Sk=,tag:u8idynYVSzxqNPxWzGo32w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeER6b1EvZTZJYTdrSVV6
            WGJOOC9PNEN2cS96eUdDVkVhTEtFN0JZWmdVCldXV0dOSVJsZG1NMlcwUXl2R2NU
            ZHN0eWNsNXRQWThYL0FPVzZPZzN5SlkKLS0tIGNoSFFqMzEzVHU1bnFMa0VNRmo2
            eVdzQ1VxQ1NZZnpDV3dnZzNRTFdZZEEKey733XiCx1cSBn9HdRKxkYSYKlQE5vVA
            8/EBxvI30v6ZApoNjeEZdps7Ujhv8UIVh2foxf5WgIRy+XIsT3hqNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T00:21:48Z"
    mac: ENC[AES256_GCM,data:r824DgWafex+CReOFoPIpOJA3CgsW4zUYiMcFVqtd5LaWFqpMUj/XMPuSIytjthwNJo+GxHb2grfp51DFngG/42k2tAqL710MQXQ0yG9ykNuBWEaSHPSmITQjXnL58xMnbHhYLyTJUZmzBLzAkENMrnYK9j0c3JbDZSV+2Ma5z8=,iv:MXcpZuCJHNbMSq9/3C0TTklH/ZbvJrDGyVZwcF8DfC0=,tag:isF23Iyj74Sn4EVoyghE3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
