apiVersion: v1
kind: Secret
metadata:
    name: application
    namespace: cosmotrak-notifications
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:UvpDue2jfYt7/9uPUHWCdI+EV1Jat2jZpEiclW58N0x3nm7r1VviY5Y75kyUlLQH3n73CMq0cqS9LxkNeKPb6erLpzkIJwrZh9dcLXKXyPsoYgxKt6wUsp21v0Kbd0BznPFwid+I5ic8d7+WMwr2fRXFgVcM,iv:e1yKOTTqfFeN2jxRClFAHrOv7I+0o1FVXu/3doO9ot4=,tag:Cs+Hm9SxIqUsOnqv8SbArg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:G1vX8mOFx3WIyDfv3w/Tu/qmybZ8phx73lqbZk0atwFZ3jVuM2IrYQNltFV8ljecw+pqXtYZl5yJ34wPvuth5Q==,iv:aJlBI5y8+SQptmK0ojZxbPJPg9OZ74LJfvWJNezgcbI=,tag:kfDqn8hCb0fOQ20M20BlVw==,type:str]
    RATE_LIMIT_SECRET: ENC[AES256_GCM,data:ShQwnLVu4wyBOnplo3StpVVcDMuXDiy6UI8S0ehBZwd09/kgC0HMIBFhe1yHY0i6VeDiy7GIZ5DMu1dKAlOz+A==,iv:xvQsf5ntUbHfguiFUAVxUj8eUqO3Sk6v4idwgmdzXz4=,tag:Ee3M72C2i25MdpXnpmkk/A==,type:str]
    TOKEN_ENCRYPTION_KEY: ENC[AES256_GCM,data:M/IODeoIkoAuu3ytAOMm1Ava4Vy8PgNS46VXMaVybFJyMgy8EEWZy75fP/I=,iv:kmgWdKnhUDMEOY8yPPs3dKv1zRXLCOkj/I8KHVlnfvs=,tag:o6PQH2uCLiiCZhbqlQ3ELA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:qYa4aMzM48XSKOsbgEzPD4PI8BYUCCs=,iv:2dXxJQztRoqsYloIX5GqKdEpraDytkkeLW3wpicY9Eg=,tag:lAYcvfy4XBbKfoQITYQyJQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:6WQic+vAALmMhrWYlSC4WkTIaFRx4tSQpO3aanF1B5jZMPrXLOa9cf5+zZxup/6mwPZkzXKfEexF7UPxmROKqg==,iv:FyHhEfXd1NE9NkXIumWCfsg4rZnzp10f4yJmSsxZatU=,tag:SrIq2OlJ5mI3ui8BvOVzTA==,type:str]
    OIDC_ADMIN_SUBJECT: ENC[AES256_GCM,data:1i0kN/ZqPxI5IRnH/UcLBsbwjhGfe2QkBdYZZ54419HYVWV1,iv:dIbVwy5Wb6lMgM0I26Ft656BTW0Jp/DVyKJZ0XNnEHc=,tag:7VtOUiziQu4QdqwIimllag==,type:str]
    APNS_TEAM_ID: ENC[AES256_GCM,data:qPUjM/RfIHp0Og==,iv:lij/i2DRcmpuNgXm/bdN4m7vQAFt8+PYw0R7F/ewhrM=,tag:K+M6cusABd9MIq6eYh5o9Q==,type:str]
    APNS_SANDBOX_KEY_ID: ENC[AES256_GCM,data:fAUPkNYY1nxDZA==,iv:EBkszZH9PnPU12/aOBcuojkFrlp93D8tOeuWL9nXMGM=,tag:1J9lsaKD+DQTamI698i44g==,type:str]
    APNS_SANDBOX_PRIVATE_KEY: ENC[AES256_GCM,data:MHXyCdy9jEIXFSxIk1j/g02Pf62bKrPA52LwfqdOr1YSVZEFueskJoX+r8omkbyaAJH5qRZEle5U767YQRyUsjNSspvPOWAMPtbCbjDrsOEjk15I6BJqRGP/9rwWplsUozFwqBSKAsjiFOgLVo2nmLuGDSnce3wA7m2jyYBUZQ2eArWqN6W0rWq3L2LrRg4SinsWKpuBuKOvqx9VeCqkdAZUDvIJdIh11jVT3+hszXhq2rQXfx529GGxj7u6wqlwhnGuFoPkJjNXVFC1liPQAhw1qZp7rYkblBKZHQo12E2prVubMOaQpnDThbXj1XhcPuOO7MzyxovRBsZkSzUqLdE=,iv:9TsTTcjM0fOdnNenZpSUKOf4wn7cB1QSU6LozO82lZU=,tag:doP+qV+MfQCxBoeY9GRbKg==,type:str]
    APNS_PRODUCTION_KEY_ID: ENC[AES256_GCM,data:/UG5NN63UYw3YA==,iv:X83iPqM1yoXvu4mdxT3K4HeoeHsbmkSkkB6T1lqSsB0=,tag:2rxFqdq7m1EZ2+eA7gBoWg==,type:str]
    APNS_PRODUCTION_PRIVATE_KEY: ENC[AES256_GCM,data:oFKaDNSlZbNQ5vKGE7BmvuzkFk74y28PPotSNucs4A6WuePbA0MwcQLh418YPZW/zqVXQCjGhHNUUv30gFiD8jMfsYdOk94CRSlUoainmlwbojQpxNmL+To5CZHg1SF96Iqd/jsMhjpXWgb+x8nsF9tODWuy5VrxtfUtqzt7w0u42cTApMp7IFCTvGjBRoA+b8ZrML1o610nTpi++enh/85zJDyFkguYqaL3ykBX3MEj8ujl/i3DPgljQQvWl1LS1TrsrejGK3y/6vKSlk/n1Qwwc2lLdaixbtUuKxoVB5kLRp3Mgb8RpZtjlYexm9ylML3aIl1dItM8cx9NmOFfVDU=,iv:+SsjGKVnWBz7moaCiI1V+yx6CZ2wwU7hoIVa7Nyt4zA=,tag:EBiKzelvbGkiGFIFCz0oXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYWFGVThac2xKZHVKTm85
            YmF1U3l6ZFFJQ0d3VklqYm5waGhFWmxwZkVBCjNnMEpsSENyNk84elpIam9HR3oz
            UVY4THJKa3FaT29WZE4xaU9oMnBlUjQKLS0tIHp6S1c0Y1pGbHpCSVFReEFkT3hq
            cGdlSm1nandMY1ZwNmNmWTE3TVAwQTgK+NYhLo6NUspirs5CbHSeDx0UZVH9Nmo7
            RXYMeOyQ5ATnoNyaQrlu3I1nCIXPx2ywHVPk57mJ1tZFt1u7cO5sig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T02:04:46Z"
    mac: ENC[AES256_GCM,data:3X9JoiOp1nSzOAK1xEZhHs+oq9yrUKcT+5h1RM9u0x/6IihgFG2EX53Qz8uB/1Pnv2jkHo3qZT22C9qiTD+qERHJlWXhC3r/oqFsKsRCYs7tTcXYm6BdLqjdupKJOpEIYJuky6Tej5SbVCMAjwK960fXaSR2/dRdsD987RivdRs=,iv:/eDxJl4wGFm+eEwKe3NLyaF13hblGnPDtbLBifTZ5bQ=,tag:I31NMgsRS51vTPLQKlfAOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
