apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: cosmotrak-notifications
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:oOdShiLFtJ9EMikvPH2Ver4M9/CISEnEMM5EF/DnRgWyU+8ZwHYK6eO7EiVFabjTy5DCLV71,iv:4QEEE5aw3oKSvIhnNzLEy6DIl2QjsMAfTjl1+RvjL1k=,tag:CEmGWB7Rc+nCNMyH8097Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOHZ2MEN6cjRYMytvQTd1
            TXpmeC9pRjZWOWdsUm8xaXprWlV6UW9WYWpnCit0ZEZwRmpndGRIYStXbXM2MmlM
            S050N2FEWXZXUU1US0FFUG5QTVdZK1UKLS0tIE1jbjFNaitjTE5XTnpPNzZSQXdU
            VDhHdXpKZHAraE1GYjJRaGIxczhvTncKRKfYKSuIAK1XNuuT7IzIzC4sBKu4kRmV
            CdZxDixq5Z+/6ENEgKLUcfp08T0wQBqLhPEOvF7i4ubSWmpfhgXe6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T06:03:20Z"
    mac: ENC[AES256_GCM,data:dRbbR10qTfohlOahmdwEoC1StbhAc2TEoTga45OQU9d2XfoqQcmZQs7dpovkBfrTwuva0uSzltuW/eEYDfDhrkwID7p/uwivE33CuTrBjHvJ+WZZxhWJU5zv326A7me60lmz0xzcuTZ5b0cY/HilnZ/OtPdg9RqXzVyaPs0IciA=,iv:PPNA7WtOVjbQqdlHaEEOtTFGnCcgkFo8ukCXEYqfSi8=,tag:pbpRrWigCTsKEoqg3cG3FA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
