apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - settings.yaml
  - application.secret.yaml
  - database.secret.yaml
  - registry.secret.yaml
  - database.yaml
  - resources.yaml
  - initial-backup.yaml
