apiVersion: v1
kind: Secret
metadata:
    name: registry
    namespace: cosmotrak-notifications
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:qn823Y9ZnEBUrMvapMvA1tdH7iLbfwzQUyANJaRmHfvzPCupM6CVRhXJJS2YBo+0M879RoSVTCeEbYfsYRJdOL+FqvKFGJA9zipFOZJn1osB95nbadcKvCIZKan+Db6W/I+fwfJJ163kvrnlF64pzLsGw6/ssUenvNFjdIZgnOhO8ZY35ep0GlitPpKS96SButMJBnFBlmnPvmmOqCaERhaDaNgpdL4+8DZeU2pI/uDPuaxrK6WjWksLdAwC/zVqSExOIFaZvWlHKlAiei6l3P4WOFwc1Dt3KFCLzKR98xrqwy79I2fvEdpSAQnlPOQBSNsjROtesiQ=,iv:yxaJ7Put8V5MnBLrilfkF1fTEx8bUhY8Jt8tMftGicM=,tag:oXxApnzjMoNJgcoIjY+Pqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1V1FLRkJEUC9yaGpEb3Vr
            WXA0RnhOeERMdUlKNkFPYUlESEZ0VG9SSlJnCkVSSFA1Rlp3a3B1Wmh6T2lJb0d0
            aW9Zc1g5UE5ERXYwV1l3MzR5MFR3ODgKLS0tIG40czRDdERRQVdacVJRQWJVaSt5
            MCt4UWZzOVpOVVlBMjFhVHMwR2UvZDgKYI9V3jAhI5Ci4ybDPCt9AgTRMxhvYvkG
            gu8xmPCCPUrN05yn30scoZAhfzbGoMTWoh0vBgkrj3Oo8Il2twJZ3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T06:03:20Z"
    mac: ENC[AES256_GCM,data:gnhQqYJT5Eyj9tbbX1DCiHmT+G7BD14M75zvujJGINwCNH+O8wj3lXkVCgdL8oZnMcgggFZ8LOcZZKR6UBHW6Y8p8H3bhx6C+Y2P0YWgGkRhdDlt5Gtu2Cm1rSQTwpu6YIy5+1So4FQDkgzmNfjvzm9W+eFUfsHTzmVXCyBT8a8=,iv:d5ErKGQuiGCS1od/N7K6ssGEdViDoeVJ8NOJv0E+iIk=,tag:83ptc1BrpEY/GItyprMo7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
