apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - resources.yaml
  - queues.yaml
  - network-policy.yaml
  - store.secret.yaml
configMapGenerator:
  - name: vulcan-config
    namespace: vulcan
    files: [config.json]
