apiVersion: v1
kind: Secret
metadata:
    name: vulcan-store
    namespace: vulcan
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0aG9jAy6peUj+5yzDEMi38b7nn9ZW1YBI2LZzqRVLg==,iv:66TfUfXgaLMJierJIRhhAzt8rPGtDnnrWqLFb1joaIw=,tag:K3tW5ZICEwAa/2/gfLtDEQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZTVpUW6eYc7/WIvA7YXaunEkKz1xyZOmZB59hmNhnhIXhY3iS4m709cjQoMyQUfF1L3Dwa4pdjbHqgirFapWAA==,iv:Iad4gAksQKiwHQTffX3xcPiPa2/IomUb9DdyA8+v214=,tag:ExoHfPfixS3vkKSRlFLdaQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NnErY3V4b1Ywc1d4T0NW
            d2ZEbzVjeUNMU2R4N0tCWVhIZTY3TDFPbjA0CkRqVVVrckFJUmR0VCtTVDd3MnNC
            QkduVEJTZXd4S3lHTExYMm1IRmpVSXMKLS0tIEpwY05tOUlJYldvSXdKSzZSM2dj
            UUFWcWNTbEt2UzJ6bzNaQ0ptZHlud28KoBjYSKnePbzOgM1uCnFik9lU7rBqayoy
            K/Sxgviedc+rrDf+rf3GIldJ1H7Vl+LWzJdnjp9pelNnS0kmJPAwGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T04:20:55Z"
    mac: ENC[AES256_GCM,data:AW1j5AEVX4P5PYHSD/K06IT4FQEkP6G49bqEdHayCcF6rzUavtUSajzjOmihXj2NOAF1oAieC6yUbhQEPSpWn056sIejqYcAmYhFe+wYFJuP5deM1D5fCt3GqAeytODA1bb8hqe1TmfAgixUwJbSQX4PqfMzNky7lA5/OEUP7es=,iv:y0yhywHp/dSC/Ba1IrgJF7fz8FcWR+pAKq24+B0nt1w=,tag:hs/mWHau4f8wX2IHzkV0Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
