apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data-longhorn
  namespace: uptime-kuma
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-resilient
  resources:
    requests:
      storage: 2Gi
