apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data-longhorn
  namespace: uptime-kuma
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/olympus-app-backup: enabled
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-resilient
  resources:
    requests:
      storage: 2Gi
