apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: arc-controller
  namespace: arc-system
spec:
  interval: 1h
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
  ref:
    tag: 0.14.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-controller
  namespace: arc-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: arc-controller
  values:
    fullnameOverride: arc-controller
    serviceAccount:
      name: arc-controller
    flags:
      logLevel: info
      watchSingleNamespace: actions-runners
    nodeSelector:
      kubernetes.io/arch: amd64
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: '1'
        memory: 512Mi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    metrics:
      controllerManagerAddr: :8080
      listenerAddr: :8080
      listenerEndpoint: /metrics
