apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces.yaml
- controller.yaml
- cache.yaml
- buildkit-tls.secret.yaml
- github-app.secret.yaml
- runners.yaml
- runner-defaults.yaml
