apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-monitor
  namespace: telchar-forge
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-processor
  namespace: telchar-forge
spec:
  replicas: 0
