apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: telchar-forge
type: Opaque
data:
    CLOUDFLARED_TOKEN: ENC[AES256_GCM,data:o1KX/NQPplfQuBhSBIaSgQV4s6R0lvpSv7eYBLYup2pvc2yJNUYxT4hGERJnIzHjAAcr+0AlYeVLDbL3KAx465fej9D3RI/1ylMGRtrGEE+MYPpbcgF/bFwZ2ZXB2LnY0Ff/XvX0X8K0XemSMWeX3Lf4QCrwbMGIlhB3tVGm5vDUIbcjY5xjm66jWeyoCstE24JQGoIQxAZX5FA0i5Uo02N0ROyj978T7ZN7wQnLtOz9Hi2HbD23EQc55OI6xijTsFb46ysRQx587s8x2vRtG5TJeMSoYzW4y1D0AdVWtXny7z/pTTE9TS2wazkpyd00p/Jwj89pqOQ=,iv:mfhESZHsNEZ9wifGra8bweP7rD3JO9nqOXMk2mluVvs=,tag:OBql5AGrymV9fvkCgEX2Hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZm5GUzE0cmJPSFk5Z0ZU
            dzhtMHZmNUp3MVdKWGhvYUJzMHYyOHQrZVM4CmJqdU9NOTlJTmcwdnNteDc4L2Mw
            Z3lGcnUyODVYTzV4aWNobmhmYUNzKzQKLS0tIHhSSW1qQ3YyV3pkbDRMK0dFaWlD
            eG9pLzR0OGpPRXFjTGw5TE5XZGtzUE0KQT1/YfI2Hc5LkEtv0lI19w/e/9xsxWKs
            J7cPB6yNdkx6CKiHw7gPGL/LcUMgHKwA0qPWg8tc7C1OcYB8kx9llA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T01:57:07Z"
    mac: ENC[AES256_GCM,data:08Xjauc5bEtS1PpKD/oJ3QU48E3KdOuC2TG8/bLlElwAdLAAepxcZUnWa8VOGKH+pjzeJsb5Gmjsl+bg94F+O6/jUP7Onh7nf6Z29VFxSfkxyUJx6ozQEz0pHz0VRv6JeUUtd9jImaPCmWeOVTm2G/2iZ3EKjJsoigqSbFCaoUo=,iv:YIfonw1osfOwpTRf5yUO4HkunpGnJnqXf8+paeCoPtM=,tag:x0GhEbC/jNIn353aidSskQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
