apiVersion: v1
kind: Secret
metadata:
    name: ghcr-creds
    namespace: telchar-forge
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:rf7r//or+hGWgm4ptLkHMVTb0B2Ds4MwhZm3JwbLw/jwLbKkx7AzJyZGzi6yheQ2C7CtLALBui7chXIRTutRjNVsOn1r/m4lITPafHXHXMVH7wC5IMP7z4sm6KReZxFKKAK5gsHGlbCZwRaSWyDPk2ZOGG0n6UD9FBlQcQaADxIsZTJjLfp5CwIDvqQ=,iv:NPO3YN3N25Y7rAeb27YhiSzM0ls2osExg0OhOPt9iNI=,tag:wBCj6Of00gBv9mfyWCWeWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTFhDbWNCQkdmaFJ3ZDU0
            UGp1enJ3dytoZ1FhV1cwUlVqL1BralE1ekdJCkYydnJ0TS9iVkVwNVc1djJ0NzFl
            Z3Y5bjlqZ0M5ZlpZN1RUMWl0SmpUeUUKLS0tIFVNQjJmZnBsUEFmUmdlQ3VXZ3Mr
            ck1hSUNHMTgvN2JzTlZtQ055dW8wbW8KqOOvEG12ocuLAW389eGwSGxZOUWonBC/
            IzqzsiZBB0HYb/w1Tx8oPxZT3GEzPgh7Ptlid9Tk/m8JuWah4bPOyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T19:29:29Z"
    mac: ENC[AES256_GCM,data:Bb8lA6OWMsUNv/jOtKapN+qbyE6jSWYyvbvz2dKRQcZ8l3Q+fCgx1uX0SCqV/sG0NqQPcviPnNiHU9c6noLiGQXsptxnV+0pGCGlBCQc2opEvTf56bYjCPi7avO4L74MJ0YAbIUe9Hk0PuMUIXqxL1fWcB9Vsh+AkqqEvViCPcg=,iv:mW7p8dVt3E/P4J5ia8A9RtIxamCF7XZP8fZnkLIsZTQ=,tag:tOtNAMqeDKzRyvvZ3k08WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
