apiVersion: v1
kind: Secret
metadata:
    name: ghcr-creds
    namespace: telchar-forge
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:PZiM1vqDEFanD6S+phGsf4QXF3h11OUjlL4cP9hvyVnu2nHw3WFOieVmzkG+IHKeUoK0CWXHqBp0EAMFtKohDWlGwDB6mKcMzXgxHC6riueu5cEJI6MY7oEZpSK08/VxTS/eJiJ0KReFrBbM/75WHYiZ/JeB5Xahh0tm3wfeGQhQlTJhbSjq1iM8XuR18Znvf/Cp6+hfVgVWxPeWQVduxSBxyv1gla+ufARYWuwlWjQjnvVJQFEFmh2SmbSYKDTij1sgw3/Qc09rCBLXFdfLyIU8QeAwo15ovNM5U4TIuKuHwVc/u4tBAxxFx9I=,iv:kJ6rhdSxTsJyowQcrGk5agCJxXnjk+tcayPYUuEvsIY=,tag:vrHHXHIyrdBiQ0m38ykLZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb1VNU0tzVGpwQkRaalNT
            Y2JQbXk0ZFdmT2Zsd3hMQWtYSGNzL3VPdGhvCllCTkpBNDMvMUdrYzFFWENOMHRk
            TVh1bFNrdGlCRXQ4ZTVFbU9VUU5UNEkKLS0tIGlYaEV2Z1JIUE1oNkpOWldFNnVT
            bml5WE5EbGp4SjRqRWRkU05rd0pOQ2cKfScKJ5akrNnYdu/kQ/W2G2ZNKBP+14Q+
            wlc2DxHrOQH1yU8g5cxUs1/qmKDmzHlZoWdYkBnGRe5VCdKfIWPurA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T01:57:07Z"
    mac: ENC[AES256_GCM,data:kd4PPSKTCa4PIxokaSfcttipV1ROUARpvrxpuOCH8K9muWuiwBvkzJf4NDIWrT0LX6/XkklhY6jX+sGKr5ZwnOyzgtEuUm8ScoMxUa++GeDmk0OqNnjtAePttXdlZ5K0o0gRvhfXQ/7z6fdd8lrrR7Wh1H5MWZar5Simp9eX/zY=,iv:qnjfJAkx1a4gSeKUjuc3SHPaTBF5QnFEQ9QOlS/Gt2w=,tag:rEpUmFqNcrJGVjcW6OSBTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
