apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-ingester
  namespace: telchar-forge
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-briefing
  namespace: telchar-forge
spec:
  replicas: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forge-config
  namespace: telchar-forge
data:
  WORKSPACE_ENABLED: 'false'
  WORKSPACE_PROCESSING_ENABLED: 'false'
  WORKSPACE_SNAPSHOT_ENABLED: 'false'
