apiVersion: v1
kind: Secret
metadata:
    name: personal-website-env
    namespace: personal-website
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:n5TjSLGfRxRCcG4jHppdZAUMlB2zgc/D31W3NCAHhGKhZ4fKljel0Uj3ry3DoXeb1kdxblJBqRgH6nzR05xx1llmiqVhQJDVf3wlT3UHFVD1JDhZ8yDCJMrAZUFE07rNp6f6I9anX+3reMGO7QD/qTMwlnlZgPH6s3JUGvO13Cxt5oPiU6yKR8Y+XQVwS00=,iv:ugaXBKopVy8pZclRT46gp90PZ9jt1F8pslrRoFtqkrQ=,tag:CqrAtLuu7gFoIzq/yOhlUg==,type:str]
    ANALYTICS_SALT: ENC[AES256_GCM,data:lLRx5SEQQeEwepBotCtaaTg=,iv:1a8InY09/qFZKFmUw9GproqH6syEo53siC2P3Prajd4=,tag:+1oCguSXgPe3YgkByO1PKA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:bkSeJBIx158DyjlfnbQ=,iv:kH5job9BC89eUZ3nw2q6jk7599N5qvII4QWsowujBjA=,tag:jVfwj0su3UHKqWD/3oX/iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY3IrVjVsV0tERjBySmFK
            UklZNURDOWdMUWhpRmQyb2I4aWhRVlFINVVNCk1KYmxsQ3V0b1lKRGxIejFDVzFa
            eE9KT0JHU1Yyd3QxU05PRDBJTXlXMlUKLS0tIHJub1ZiZEh1TnlGemtZTGliREZ3
            L2RDZ2cvTjRvUVBINEZxckJpay8rbUUKq0e/PRUduAMpKT+r4BimgZa6WP8o+H0O
            5IUXAdiTYPdx2roUZPSPOINECZ6KrnFSlUkBkJ/ty3oD0Q8q/fwMmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T05:10:08Z"
    mac: ENC[AES256_GCM,data:YkSW7gCf9jtBYIxU38qpGHy/GhaMw+ocawYPjHnXJw1a5J/U068yetTO6PXLaXumxF0OlLgMYSan0VhjKSqjsqfDtPnnaL3Kx1+6kBQYLYSDoUriAnPdHhOgiH1arNsDnBXYn8Vduol/JkAvT748fqG23iL4M+IT9RaeOgbXfdg=,iv:EULMwbXjfFuB5HmEFefoYxdqocjX7NRGs3+izvXlwrE=,tag:EUp2ApMaMDk4qnqDOXfB5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
