apiVersion: v1
kind: Secret
metadata:
    name: personal-website-postgres
    namespace: personal-website
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:NfdZLZdWFNAM0zVFxJAAIVlrtu6LYsqvwjZUKo5ynpwbDSN69E38hcqInThelsZg,iv:W3cb5hxHXK8Vl6yrkJWjm2GUhyKCIW1HzdzPyGjnYpc=,tag:a73s5v4N5xgCeEeoJRMCbw==,type:str]
    POSTGRES_APP_PASSWORD: ENC[AES256_GCM,data:kHaZtWmvW0/uchDSTcUMt27k55eAPe5bW9M/t6OE9wFCaAVcz5F4K3VSKCqQuiaq,iv:wjzGF2HwnOluguF11btR95AggBorYHDjdoGwO+V6e/8=,tag:T0Wa7naGLT9reTF0rt0q4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNlVoQ2xJMzkxTjBCb2tK
            MGdnRCtiOWg2aU80L3o5SUN2cE9kaGhUbGg4Cm5HR1k4VkN5cVhkd3dNeWltb2U0
            dllxVG16dkdITkZBUDhaWXk1OTJnYkUKLS0tIDdMZ0Q5OWQ5b3N6YjB6c2RvbDY2
            VlpWYlNIQ0JQK2svdXl5SnpxT3VrSG8KNwUKJisbeP2BQuP2/ZUnLsVPO9IKRqRA
            FX66hCfQRXhsgM8C0V91vHw9hCRaLwyJpXhQT1c5B+yHELKcspTz2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T05:10:08Z"
    mac: ENC[AES256_GCM,data:SrhvDMIqqS5WWdwTdl1YpkFY3QpTNlNqhLAnh+9eb+8kIz0IlPbSXVP6wOh18DG+oLeR+uk2dxDN9aWcLru+2Iam8p+zKRc26FNQ7X3BUYOd54mL+1Mue/m0S75/qruhdQkHVLXKxkqx0mddnvlNQthnnCirDFmTFb0lL2rCQUA=,iv:WQj83VhzAE5yQc0UdYlayWO8d7jh1fSsnwDUTF/GGcE=,tag:76lqxZD/CWe8fouxopuO9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
