apiVersion: v1
kind: Secret
metadata:
    name: personal-website-registry
    namespace: personal-website
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:uFnk0hdum4vy7loaTznNORqYqahCccgC0dYI92K83kwScrw0gMEaAVOvS4aVd2/TtV9fYr76gX6aQKIpVuITp8dmOrhNDX7kh4Qx0YOmD16smUcXM5WFFGNMGtPRE4NKIrLXxENexxMaEVAWNXzKajbQB9MLGDXaK735bfe2ELkv4kxkLR5kKHc74tHonfFfEiZ/x1sU9kIw2UUALkj7AOx4xtkUwvYX4FOLrPS4GokqAzMkLRx+6g==,iv:PPqyQqEEslURWcvLjV7JzX6V43fK/gghB0TqpHJqPnw=,tag:NIX375GPKgYvPTRGp1UUSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYnRmbnFRUXdzYkdyaTM4
            OTh4cVhJSVFtSzhmQmdIeFZrTXV6NVBLaFFJCnNIR0NzdHd3aFFjc1UrZWxkS0lU
            R2hTM0I4cnMrMG9YZ29oeWNYVmJxWFUKLS0tIEpPVFpTbS9mTjIvZ1JPOWFDUE1R
            N3pkNFlMb2tkTms3N080VUhqVUExQTAK0J5w0qB4Ev3/X/0a2DaELw6DHtDyVrxS
            MYUyHoRVYd+uXyN2W8bYh08lcXyKCnf+YA5Klnmr9OgPQP37aSfFeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T05:08:33Z"
    mac: ENC[AES256_GCM,data:fVv0EzRJuWqsZQxMDfChKDooLGXKcxpK2zS0bgV7S1tv2qhrniR5CCtcTy5J+cOicetAWyD/I6U1qb+h+jLWlhNudhqYA3NNA7lg/A96/GSAHatBp0RN9pbxhmZCF5kUftL9DAYeTDaHE1UecqnFx05HW5JwVnO6kty63hlF3TE=,iv:tTbhSfOydjBnmtkV/bXuaf3FejR/fJAixrTriiE+Ijs=,tag:Tpf4a+0TxZ/uKywUBNwQUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
