apiVersion: v1
kind: Secret
metadata:
    name: coder-secrets
    namespace: coder
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:q+MHMDsAirm+f00cBznh9byrhLi6RwBt40G8ObN9Lz02ikUIb89WNMM15Q==,iv:tl6S+lS3x9VETg2thVtpk2dmECITsM5q7Z+QaZP7two=,tag:zxpwyTcNNP1Xvv0JVstvYQ==,type:str]
    postgres-url: ENC[AES256_GCM,data:47DM1YxhdtmBcRc7er9CUDTB0s4oqEyCel8KusnvrrUEhTY23QxdcjBQKn6tNhP5ZfN3Z8Dq/qzvuR45Cxa8r2oeLlVzU8Mt5qhOU7oN3NoLyzk7uTRczU5MVW7c8LaVr2I+uV5Q8YpoONZ1VurctINhkrIlPj9ztB/wNml5,iv:59nVpE68aeACBm7MyBK9SbSFJTYuxFOO7klEXc18qUE=,tag:QKUmdRWo1X0vXY3H9Nljlg==,type:str]
    token-encryption-key: ENC[AES256_GCM,data:Dx62YPxT85qZRK1MhSYSMEG30KVFu16zJp5PwYx86iECROso1/EXDl69xBY=,iv:gFBuYK7JvVLrV9eA0MhigdvnBrMMPr/1v3Vge1AjNGQ=,tag:KFJT72mB0TbUGGmpRe1ecA==,type:str]
    github-client-id: ENC[AES256_GCM,data:icsdaq5NIkQ5O7w3Ahzgn69KXTU=,iv:PQWoyAjDx9O2tYXsKqyTvywniNW54UafbU+QmP47TWU=,tag:vrDsfvqYBrLpmjEPrQzijA==,type:str]
    github-client-secret: ENC[AES256_GCM,data:u8lmGPRSHDlpQt9P/C430onvqKSrGO/n3qe8jOm+kt7GH4N44TlPzQ==,iv:ltD9IIbvqQ/slNvTlb2FEWipxDZ13fhdc/nkBuQhCoE=,tag:mbSEpvbdm4fx2R2owK/mQA==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:MR07vYndi4NuP+93vALyNcJ94Hil5DH6Nxkes856,iv:gwza7xOiTaP26E3K6PnS4Auikhngm9QLZPdosemFsvc=,tag:KjI5HA1MkW3AgKLx60nsaQ==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:ToK7iZgoNJwaoDXd+dHXDxIeRVeNikCjeGnlOmLx69lmmUacvc199TtKGtjzoKWXKxiFjnNmf9Qr4f2tRLzMJQ==,iv:+5pBhZtjlnlNbpfUx6RN/vTFNW5kT0l6c5b3/G2YYjg=,tag:TgjTyFB6TiIPewXxyimlYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N1N4bG9MK2txN2wxeWc3
            MjRBczhTUHEvVDVtaHJXdzU4Z29paE42UWxnCnhwOFkwa0JSbCs3MTlheXpoQjF1
            U3U3Mis2YWtzdDdmWUJsL1F0MlhXVDAKLS0tIHI4MlNkbitaVkV6RU43eWVaRGFz
            MmJkMWRkSjdENDBJK0NzNERrTnRvZ1EKuIOwd7H+k9eeJMhvbcB5hcuhwZDYDj2k
            PK2lSaWSNsvcGdJJJLDgQqsYu/oph+Ed2Vwx1ZTfuNxcOjlIIHmS/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T07:13:17Z"
    mac: ENC[AES256_GCM,data:KQv4bhy6H1ryL067OmSIER2OFaRJWjRMZqeH2eY64a/CoRwTBPxb1Ebj45JKP1EVH7o4MrJq+OIZuXhnPHJLuuqstKo/AAYp27GMzwLEcpqFCiIM4mkTi+ZP8H+ln+8HcYTXUYuaKM8ssbPpx/ghM3tC1lA7oMmDEr4sZCls0+A=,iv:WEfg4ETT8sGZoXvQvjudqXtN6YP2FT0zEAWu2kpv3T0=,tag:JwSHuJnIN/1bqYVM8ZvngA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
