apiVersion: v1
kind: Secret
metadata:
    name: coder-secrets
    namespace: coder
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:q+MHMDsAirm+f00cBznh9byrhLi6RwBt40G8ObN9Lz02ikUIb89WNMM15Q==,iv:tl6S+lS3x9VETg2thVtpk2dmECITsM5q7Z+QaZP7two=,tag:zxpwyTcNNP1Xvv0JVstvYQ==,type:str]
    postgres-url: ENC[AES256_GCM,data:47DM1YxhdtmBcRc7er9CUDTB0s4oqEyCel8KusnvrrUEhTY23QxdcjBQKn6tNhP5ZfN3Z8Dq/qzvuR45Cxa8r2oeLlVzU8Mt5qhOU7oN3NoLyzk7uTRczU5MVW7c8LaVr2I+uV5Q8YpoONZ1VurctINhkrIlPj9ztB/wNml5,iv:59nVpE68aeACBm7MyBK9SbSFJTYuxFOO7klEXc18qUE=,tag:QKUmdRWo1X0vXY3H9Nljlg==,type:str]
    token-encryption-key: ENC[AES256_GCM,data:Dx62YPxT85qZRK1MhSYSMEG30KVFu16zJp5PwYx86iECROso1/EXDl69xBY=,iv:gFBuYK7JvVLrV9eA0MhigdvnBrMMPr/1v3Vge1AjNGQ=,tag:KFJT72mB0TbUGGmpRe1ecA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N1N4bG9MK2txN2wxeWc3
            MjRBczhTUHEvVDVtaHJXdzU4Z29paE42UWxnCnhwOFkwa0JSbCs3MTlheXpoQjF1
            U3U3Mis2YWtzdDdmWUJsL1F0MlhXVDAKLS0tIHI4MlNkbitaVkV6RU43eWVaRGFz
            MmJkMWRkSjdENDBJK0NzNERrTnRvZ1EKuIOwd7H+k9eeJMhvbcB5hcuhwZDYDj2k
            PK2lSaWSNsvcGdJJJLDgQqsYu/oph+Ed2Vwx1ZTfuNxcOjlIIHmS/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T03:14:53Z"
    mac: ENC[AES256_GCM,data:iqNpjJd0vJcNCQ9PQqdo81hFJZ5EmE+QVATQ2skTC3XFOlozXql2flFZsvOaxrVXpNh468gwOJAANdsD9FPNdfasayBmc3NUg8FZUrGxLXnEq/ZCScX+wUE7iLAvWuJkbVI/O3zVKXX7J9X9MXUuRj7Pe83ZG8LZ9StRQuoOVAU=,iv:/Iw0kTKat6xY9bao96qRA2kt+TWqoDh5ylR+7L1asjY=,tag:JGvgrVXc7Sb7I56k8cWn6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
