coder:
  replicaCount: 1

  env:
    - name: CODER_ACCESS_URL
      value: https://coder.jacob-neel.dev
    - name: CODER_HOST_PREFIX_COOKIE
      value: "true"
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-secrets
          key: postgres-url
    - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
      value: "false"
    - name: CODER_EXTERNAL_AUTH_0_ID
      value: github
    - name: CODER_EXTERNAL_AUTH_0_TYPE
      value: github
    - name: CODER_EXTERNAL_AUTH_0_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: coder-secrets
          key: github-client-id
    - name: CODER_EXTERNAL_AUTH_0_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: coder-secrets
          key: github-client-secret
    - name: CODER_EXTERNAL_AUTH_0_REVOKE_URL
      value: https://api.github.com/applications/$(CODER_EXTERNAL_AUTH_0_CLIENT_ID)/grant
    - name: CODER_EXTERNAL_AUTH_0_APP_INSTALL_URL
      value: https://github.com/apps/olympus-coder-agents/installations/new
    - name: CODER_OIDC_ISSUER_URL
      value: https://auth.jacob-neel.dev/application/o/coder/
    - name: CODER_OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: coder-secrets
          key: oidc-client-id
    - name: CODER_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: coder-secrets
          key: oidc-client-secret
    - name: CODER_OIDC_SCOPES
      value: openid,profile,email,offline_access
    - name: CODER_OIDC_ALLOW_SIGNUPS
      value: "false"
    - name: CODER_OIDC_IGNORE_EMAIL_VERIFIED
      value: "true"
    - name: CODER_OIDC_SIGN_IN_TEXT
      value: Continue with Google
    - name: CODER_DISABLE_PASSWORD_AUTH
      value: "false"
    - name: CODER_TELEMETRY_ENABLE
      value: "false"

  service:
    type: LoadBalancer
    loadBalancerClass: tailscale
    sessionAffinity: None
    annotations:
      tailscale.com/hostname: olympus-coder

  serviceAccount:
    workspacePerms: true
    enableDeployments: true

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 4Gi
