apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: satellite-data-prod
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  path: ./apps/olympus/satellite-data/prod
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
