apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
data:
    client_id: ENC[AES256_GCM,data:wFdkaQ5DouU2SJuJoSt32rLhklN/HChl,iv:tJ3pL1dL54YoIyETxLS8Cr9o/OJDmgcTZ8apDXWKSmY=,tag:aoYbtsCkVV4FykQ70E1AvA==,type:str]
    client_secret: ENC[AES256_GCM,data:ebj1aSANe61KRNQeAjcgnbSpFsTUmfwN2xodMhlgdJtZTNozVcrefwsD/xuL8o/R+Aw6wSCFz/kTSUsMivZvX2Kn4bFo/eDHcM1zioDsKD5ZmG/h,iv:MxR51SgayYoQn8IpqzCCAhCWNaSfnkqtFUlGNnq4E1M=,tag:Pmdhpay7gWrUIBRWuSU4uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SElxTmtDWmxCQ3FTWE1I
            d0FBTE1RV3BYYldzZlRtNktHNlpqYkthcHlRCjg1SnNmOXNFampsL25tWVpEd3Va
            SEk1ekFLYmZBQlM5eEZpU2diVUtUclEKLS0tIFEwWGN5YVU1ZHYwdDJjZ0pJRnVQ
            T25PcXRMUW9OMmo3T0dYMGtzOTRCcTgKW/kKahxx51ldLBs32ktTq03v92itu3jf
            s6vNWhZ2P6/1K3M4MblLI5hltJxP2cW2G8TkapM9WE0MalU7rp84wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T01:57:05Z"
    mac: ENC[AES256_GCM,data:Ksw7zmN1qKTFAL1xPmYMz5OhcOt+O36rPU6B+zcrdSGV05zYo/RZ2wpgyR5vm57dhMuJz1RfmEMhuEUoty8+vddxHfe/wz4nhF3u7NJNLGM94pVRYsURJLjujF03RC442uJW/JxJHWcwGDyEP5vMr9HS93bZR/S2ow4aVbQguTw=,iv:1X5UZHEu4Xujo2RTzIJq3ZUFnp9RMsIYgpuCcHfO85E=,tag:ntZGd5FFzPGJfq9PMTgzsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
