apiVersion: v1
kind: Secret
metadata:
    name: pihole-api-password
    namespace: pihole
type: Opaque
stringData:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:aqvz1xQbKzn/GBGzbDM=,iv:9Gz+ZvGgOm7148lNbkvqryAueqdiqMh9YDXbe0eJGww=,tag:qiC0Ey2UxkBae5VQ+juJSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWTB6ZVBrR3RoSEdmaHlT
            ZzRrSjFTRFY5TkwvemtPT1Y2SjBFRzdkbFZvCjdnSDRlSnNTWGdCUG9UYVRWRjUr
            U01pOExoMWlKZDlGNSthc1ZrejRwZHMKLS0tIFZmSzNSaXRkWWRBQjBZQUZyRDhD
            NXFFNlUxaG05aEo5ZERpVXp2ZllGVFEKufqBRIsrJKiiCh6tfDD7w/5hRTl2Fmr2
            9JnLLkAnu1f6IjJ4bYb+zbyjRdGNslRFFRPC38i6mEpOj9qeT2WETQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T01:57:07Z"
    mac: ENC[AES256_GCM,data:B/e+BIxktnhWzI2rqXjgB3yi7vVOdstcEEHmS9b3mKD864aeOWkTdCkhi95Y8f/dUo8LXifNIiU2jt66phOqEJxZa8m4lg1299kro5z7/eUVmdmhr9A8Fw6WagL+dMhHMdE7LEKn51+5Uskf9zWBVNCtGYojANhLwjA2jpC9eFw=,iv:ow4ycOBoPEgXGgOMER39gVGfjRiNnpqfDxlvOBahFr8=,tag:jePAQIKZu5btdlUCAnq0Pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
