apiVersion: v1
kind: Secret
metadata:
    name: shaderweave-registry
    namespace: shaderweave
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:TRj9MlRUIRZWSvcHVYl23j+wS2zwiqLwF1J5Fl0QZt7EUK1rj/afgjuXlV9tNQc9RJByc0zVXoRiSakrt+XibaoKOeSd17s2Aln72HyiU4BiQ5BM6BMlCkNP3ULfrTkfQUJZTjwyGElDB/7smkaKS6BI2/nus8781/amGaic2w/zBA4HuRZUTW4KIWQcX7b+MfjeyJf+i3iZycFNMP7Fz2A4amqq79WEXOAzH9QlZkMexVO0pFbS+Q==,iv:OK4+QT1T+aOUKcAGUQ1b07Pdz6jz/MQDnYOO7drRkIw=,tag:1oLSZEq897j8PUvjl+hGXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUFlDV0c3WTlaOHZpQ1VJ
            YTU4YWRoSW92c0JLM0xiSmZYdVlieVd2V0g4CnVETGJ0dkpOVk44RDFhZUNzbGVo
            S1RxczBxSUltWjhDNkZTRllTQUxKcVEKLS0tIC9SdVR0YzZBQm9ZdXJsdjdqSGsy
            U2sxQUlzN0hLWkVPZVlSVU80US9WNDQKBsty67+odPrFw1akXBw9jDBEXsEFrftp
            mzC/kGAlo1xiGNpQmVI42lDSi4xPCdP7h8F4ra60h3TYYhsQPPKpOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T17:10:04Z"
    mac: ENC[AES256_GCM,data:7siMMbDakKMrlQP6+zH6nb0I+ln5DAedapPA7f2o+g+xNCEKI9qzioKoWUgv46eQKqpi/N3HxOtl/i5gobC9ZR1RGLdwta+E6iFrSYEBu+soUdzNh3kXO8RpYQBmmY5cyCnsr8HMlF5DnoP0cmj6m9noKYZz+ahRIhc51QB310E=,iv:7wWaYqdmC12aQtS+ATLjBChFRbiummxKUzubyt3jpH4=,tag:jDqamCtEnS43PMjGb8RqWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
