apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: netbox-db-backup
  namespace: longhorn-system
spec:
  cron: "15 3 * * *"
  task: backup
  retain: 7
  concurrency: 1
  groups: []
  labels:
    app.kubernetes.io/name: netbox-postgres
  parameters:
    full-backup-interval: "7"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: netbox-media-backup
  namespace: longhorn-system
spec:
  cron: "15 4 * * *"
  task: backup
  retain: 7
  concurrency: 1
  groups: []
  labels:
    app.kubernetes.io/name: netbox-media
  parameters:
    full-backup-interval: "7"
