apiVersion: v1
kind: Secret
metadata:
    name: longhorn-r2-credentials
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:D3+QxEFnSRXh/QUMBBIcuc0brzCyE0J9RXL6lvSKST4=,iv:TbQ1rKlCkmXtAiEna9uMzXgK9N0xEDD2CI/9rKoKbcE=,tag:BFU/5kuYSg4yYIwOfTnOzw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pWURLkbOO3OCavcMiQpfM4FlD7exS/1Gkc0dfiWHjq/zHVWj6WuSf2tmZZq7zZq8e7D+79lBm3o+wlk+VY9ayQ==,iv:fu0M0Ma/L+93NwL1cCRWD3RHkI9meaN+9u7K5u3KuRo=,tag:BFn3/VzXqyjBL87ymUPlsQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:dZh46bicMlZ24baG4eDbSGrVk7m2Rg5pyN2mvpUq4aEUFAG31gBc9Ch2CQnf7SKV0hzQDJwuFFNo9g6wZuniQhg=,iv:8WLC4nFMkpDybBuznKnobxqcITWEp5kcVAjF4hf0Cyk=,tag:buQ5uPzzaJN5Qkf6ESij9g==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:+dm54K0=,iv:x5EYqZVVjGnTudSaESfQuhMqM/gZGGLHnbvzuqAHxN4=,tag:kqruJEmZSQb/lNs0+fg+pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVEloYitMWml1dTRvOVBM
            dDBqZFBHQWVaZGFRSkJVS0gwbVJGYWt0L3c4Ck93VW94SUNGdTBFZWlnQTN6Z1kw
            Y2h5N1ZucjNpdE9HYXBnczhoaHBhaUkKLS0tIEc2TDNtVFdETUlKY0ZVVmttd0w2
            QVJUcFpwNm5tRGtrckZZeEtpeHRCRkEKMLbeLvQJfnJGcOCo4O11Yos0SgTAlR6Q
            zBc2TDeSF9aC9c9x420JvOvQ4U9nhUE9dcbcjtOCQK9Y2We4mTbnQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T04:20:01Z"
    mac: ENC[AES256_GCM,data:GoqpoBwkjspZfV6LQhKMRKNk7e+pny1x0FyZww45iFks8/Q9+oym21LGSY+ZCQfuCwemW0xRapuFl9gMQBKcQc39WuBIW4qbBgu+MOkE6eofTHgxkSqnPY2fyTH+LJ+ohj1uXxAL2NnRDOfdxnE3aE9xH87sEMyYyQqVD60SYEo=,iv:9Cj0M+Kh/G1iMMsvJmmstDeG9gHhtQGdk4HxBs3UAfQ=,tag:rp4XKf6BcKHvUwCY76ZSVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
