persistence:
  createStorageClass: false

defaultSettings:
  allowRecurringJobWhileVolumeDetached: true
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 3
  defaultDataLocality: best-effort
  replicaAutoBalance: best-effort
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 20
  upgradeChecker: false
  allowCollectingLonghornUsageMetrics: false
  v2DataEngine: false

defaultBackupStore:
  backupTarget: s3://olympus-longhorn-backups@auto/
  backupTargetCredentialSecret: longhorn-r2-credentials

longhornUI:
  replicas: 1

service:
  ui:
    type: ClusterIP
