persistence:
  createStorageClass: false

defaultSettings:
  allowRecurringJobWhileVolumeDetached: true
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 3
  defaultDataLocality: best-effort
  replicaAutoBalance: best-effort
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 20
  upgradeChecker: false
  allowCollectingLonghornUsageMetrics: false
  v2DataEngine: false

defaultBackupStore:
  backupTarget: nfs://10.0.0.5:/media/DATA-1/longhorn-backups

longhornUI:
  replicas: 1

service:
  ui:
    type: ClusterIP
