apiVersion: v1
kind: Namespace
metadata:
  name: kueue-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kueue
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry.k8s.io/kueue/charts/kueue
  ref:
    tag: 0.19.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kueue
  namespace: kueue-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: kueue
    namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controllerManager:
      manager:
        image:
          repository: registry.k8s.io/kueue/kueue
          tag: v0.19.2
          pullPolicy: IfNotPresent
    managerConfig:
      controllerManagerConfigYaml: |
        apiVersion: config.kueue.x-k8s.io/v1beta2
        kind: Configuration
        health:
          healthProbeBindAddress: :8081
        metrics:
          bindAddress: :8443
        webhook:
          port: 9443
        leaderElection:
          leaderElect: true
          resourceName: c1f6bfd2.kueue.x-k8s.io
        managedJobsNamespaceSelector:
          matchLabels:
            vulcan.olympus/managed: "true"
        manageJobsWithoutQueueName: false
        integrations:
          frameworks: [batch/job]
