"""Regenerate Kueue caps from the gateway's single policy source."""
import json
from pathlib import Path
import yaml

directory = Path(__file__).resolve().parents[1] / "apps/olympus/vulcan"
config = json.loads((directory / "config.json").read_text())
objects = [{"apiVersion": "kueue.x-k8s.io/v1beta2", "kind": "ResourceFlavor",
            "metadata": {"name": "vulcan-amd64"}, "spec": {"nodeLabels": {"kubernetes.io/arch": "amd64"}}}]
for identity, profile in config["profiles"].items():
    resources = [{"name": key, "nominalQuota": str(value)} for key, value in profile["quota"].items()]
    objects.extend([
        {"apiVersion": "kueue.x-k8s.io/v1beta2", "kind": "ClusterQueue", "metadata": {"name": "vulcan-" + identity},
         "spec": {"namespaceSelector": {"matchLabels": {"kubernetes.io/metadata.name": "vulcan-jobs"}},
                  "queueingStrategy": "BestEffortFIFO", "resourceGroups": [{"coveredResources": list(profile["quota"]),
                  "flavors": [{"name": "vulcan-amd64", "resources": resources}]}]}},
        {"apiVersion": "kueue.x-k8s.io/v1beta2", "kind": "LocalQueue",
         "metadata": {"name": profile["queue"], "namespace": "vulcan-jobs"}, "spec": {"clusterQueue": "vulcan-" + identity}}])
(directory / "queues.yaml").write_text("# Generated by runner-service/render-queues.py; edit config.json.\n" + yaml.safe_dump_all(objects, sort_keys=False))
