apiVersion: v1
kind: ConfigMap
metadata:
  name: olympus-gitops-info
  namespace: flux-system
  labels:
    app.kubernetes.io/managed-by: flux
data:
  cluster: olympus
  repository: https://github.com/link2427/homelab
  branch: main

