apiVersion: v1
kind: Secret
metadata:
    name: homepage-media-widgets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:x2HnLqo2VJbtarssBGR15PcUfQHqx1HT08W3LS0MWoimkuFRdRORH2pX9OxI8JEEgbtKJm8uv254sN++du1WKweZLRw=,iv:T3/bpkv0rCIf3OkKypNpAZh4xwvqj23PK1hRAkJbkvE=,tag:HkUwPQMNNOF3aMxCqDF1pw==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:Cd4EuHis+6Sc+C71Iw/0D2ttTAs=,iv:QsAgPZGTgDu3SjYNuBKjksn0QCd2aemK6NZdjs4t/pc=,tag:Qjkle1tJVs9Ve1Te6fttDA==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:+QmvIFI5JIALeCJIpiHZdVbeE2uk6Cuh8LFXcsQRFsM=,iv:DgeDJH7bq1tYO1C/mO7IbVEr20fnkAvbq/zwcoK+Nyc=,tag:AnP+7UgEenkRBrOF6u4zuw==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:AU+Gg9+yySMuMfgxSnhDP60rx3FFoT4zCVk4YKu53lg=,iv:4Pmh0QrhHB890zSqZUVi7GsCZBaQ/RB4sXQ6uZdaueQ=,tag:fAdLPfAip+J76kujqrrTYg==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:AdvPc5F774FIQ1PfwOLoKh44RPAgxHjXEqVoIVzC6Wg=,iv:aTUk7pgTspwom/DzY0/NegRyTi1lTcMfuvzuYRgetlc=,tag:A0EZ4zJPOEeoM6ptVoz/jA==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:8bBPqLT9qDPCFFM=,iv:d7dP+pSmX/FKLiqiTWX839PWQRqmkNBPv+ZK2ZWpqLc=,tag:2Cgrpp19I++09PqoPd0bEw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:2JokO52Rz7fEpVdiKZDMHD+QhBDTTCN2hE5UVEb3rAIN6+Q71YJ2TN9tUapYs3sQ,iv:UI2ACMuHfc9kei+OJaWzmKwzU6lQmznqZpvMA2xsD28=,tag:Rhr/bU1CtTi2NHotB4tg2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTWlZdkZZeDgzWUpyUjhh
            MHN4OENwblZhYWxDekNYU2RLdkQ1MXczbERnCk5kMFc1M3huZklqYUZ1VTVOQ25D
            czNmQkx6blUvOGV5TnBaaCtCZzFtdTQKLS0tIHJzcU51QmRvN2ZsNGZmSVUwOTdB
            MlZnYkVVVkZUT3l4dDNseDlUcExxNTgKB40HNNwHeSOAoz7V8nuPZ+c2DR7sJJXs
            rtALEu+AtID2BtU0KKmOztlCacAkY5FwP7DjpaH74SxsriRt5iDocA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T00:36:08Z"
    mac: ENC[AES256_GCM,data:WSLv8rqQUV1L+3z52Dn1bJY+SnNM4M7TqDQTUxHe+NFaYYHjCjvNDf4hHGT3pjpm2H4snb9JxuEmSzTs6arfWapQ7O1G9fp2DcFlvOwEvqPwiqRd9lBVEieqKWcszjWHOK6YjNd5rBqirJY0m8f+v7IpGRCj3RxGT+LfFWjT0yk=,iv:kUldt7CmZU2ppGoxTDdSj0gCcSbjHROrCS4fUs+iyZY=,tag:F6+3vNmnmSEaNa49iagDQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
