apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-longhorn
  namespace: portainer
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-resilient
  resources:
    requests:
      storage: 10Gi
