apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: telchar-construct
type: Opaque
data:
    CLOUDFLARED_TOKEN: ENC[AES256_GCM,data:EKaPIHC01Kdf1PskY7FLC3r2R3wV6nJiqP82fwrQoHSwJR9DOUXOHCAaulKTWTi2ZsdTgg0BJTXl6pjObjzBsq7vLEpLceudts1FHZnE2kXc/H7IORS4dvp/9EsRuB3qmA+46bLxtnw3NWEKYR7/Ds20foIcP+FGa1XON9acyuvkGSsWbPkW5MdICRd0wiGq6eXrpRUkzBrhKvpaJ3kqDaP+NrlrxXVtTjcxlPK35etkQar9gSQPBEauGqxC9VJpuO77BjRlmuzGu+lmil5KlaJZVu/WNJ3R49+BaumA9Vu4MnzxCH5bjkdyE7kf9T+y+OWLmgTmJCo=,iv:qarnOMu05OgmRkWnmjxR6Gmf5lIKYy5/2ER92+BlXfQ=,tag:KNkpEhqFALfKraRtPVObQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByby9melJSampvbWtlaDBq
            c1ZnYnpINjRoR29oeHZYMW85dGNFa2RjRWpFCk1SMkoxMVg3dVl4dDZPS2ROdk93
            cmRjSmFuZG15aFNQMm92WEN6NklOMUEKLS0tIEtTOTlkOUJvRFNGczhXU3F2SjZo
            OTBiVUYrQ3Qray9zTDZubGJiL3BNOVEKOssSn6u411AIn7ouDwzf6CxI+0WsDSaH
            ln945mnzSnK/eqhhnYDjEASHd0NypjmOmeH1eLd6v5k3X4Xd9wcVkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T01:57:07Z"
    mac: ENC[AES256_GCM,data:pFcVLIvW6oyQbpJs3Edjx1MVY5AcwhzjIjzizwV53gnhyJa/JUdBLTeNP2y+XRBIJY1l12tYoZ0BuA9czR7AFAOPTFXw1bz3mcGco763hEPym5Xcji8RhWZ1Bmb6ZGqI6iU/Q48o7G05xgsWIEBmKTr10A74wjh2K4em02xzi6Q=,iv:6vY2wktsx0r+ZIvatLDERry/71uEaLEtTK4Q+J+H6jM=,tag:uAjksKcEn1iE3UC+HBfJ9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
