apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - seerr.yaml
  - servarr.yaml
  - qbittorrent.yaml
  # nordvpn.secret.yaml is added after NordVPN service credentials are encrypted.
