apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - seerr.yaml
  - servarr.yaml
  - qbittorrent.yaml
  - access.yaml
  - servarr-auth.secret.yaml
