apiVersion: v1
kind: Secret
metadata:
    name: servarr-ui-credentials
    namespace: media-automation
type: Opaque
stringData:
    SERVARR_USERNAME: ENC[AES256_GCM,data:kdaRFRUgxQ==,iv:RfxTUJc9hNXkiLw67kgkETL3tfj/mAc5ZDSvPBSb6Yo=,tag:qM434fs9sY12HcEnEsRMsg==,type:str]
    SERVARR_PASSWORD: ENC[AES256_GCM,data:EuRdnX55eFT+7epwPlKJSTyuG7BmSgmcALtGk/E4YJEO5jmJhKPCn+35RQ==,iv:MUw43I4sIeIBXE/5N0mfVuQHk3gV24UpdEzw4LcVMig=,tag:6nV/VwS59sou47Gir6sM1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUHNTOUxEb1UwNXRuc2Ru
            TnpUZ05Zc1ZLRHdVQjVVbHc2U2IyV2dkRlIwClMzVSt4WS9SOUROUUFsSVRKQ2Mz
            WkVVeHNRUndYdUp5cXhib0VnTnZFM0EKLS0tIGoxV1hKQ1ZkOWNVTXhoK2U0WHBo
            UEVYa1hpbDJvWHplZ1gvWTJMZk5McGsKNbSoo8qAsye4l/UHpmq6yznQf1h9ODte
            GL4/MgRY0K/hEBa/R5i5LZ5E4V5Tn+28V9+1QKjpB/sqdGrHh+bBTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T00:49:05Z"
    mac: ENC[AES256_GCM,data:mgcki7i9Oh6y39rXV1LNWCCJCblu8XmNsWd/F3FeqwVySKJ0hUqXbbnntxkSgu50w7xiIgQReIPQtWRsjxgBi7ApFrKtaetoL1pG0fg7KiALhoYUV5J/qgeA/FVM8E7sPKdw+qNCSa/ZYNuLtKevRkGUs3jmG3oqUH3RxO5+DYQ=,iv:O3lDEgfW4C9w+Zkt1K01tiu3naDD69LLAxMzwFv7Okc=,tag:Dt7QA07Bez4RG+vLu2f+6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
