apiVersion: v1
kind: Secret
metadata:
    name: vpn-egress-client
    namespace: media-automation
type: Opaque
stringData:
    HTTPPROXY_USER: ENC[AES256_GCM,data:MRX9jsOiwP3fVs0=,iv:TBsM50AaoQLqEaOCeBiYp6eR5PBrxVP5s+qQu5lxo5U=,tag:9rJiL9gv92uxFHD5TjkuHw==,type:str]
    HTTPPROXY_PASSWORD: ENC[AES256_GCM,data:WEHFkGvmTZgEVjztVbiUqhDlNF0iDkDvjkvn90gW2vxcnx2jkW8lGD1pgmXqqfWo,iv:VUfWwZwpnbvqP/y5hX6R5BjCJoLGp5AWBcJlrI8vJHo=,tag:nK1fWJZ5ZN7A+gxgQPGUIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN2Q0b1l3aWM4TFRZbXor
            UkZ4TGxrSEdEZkdqVytIbHBTalZWUHp1emo0CjBVVWl2UjB6clVEU2hXSzVRYnpk
            L2ZyczBwa2MycGgvVjFFeVVMRWhDTlkKLS0tIFpoMWJhSVU4NVFXeG85a01DZGpl
            UFdaUURGcTZLeE1Qdm9GMlVrSEZKTmcK6enmKPM3JHGxLBJM1iKADvu8T0ekOyps
            E7yeE9nOSdlRENYw3ym+4pmn0260itnnx6ui8VNjNY2NMTPTTmrdpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T01:04:55Z"
    mac: ENC[AES256_GCM,data:qGAhsFk8R54bN3tXpfpO8SNb7+b4j/reyWoFoN1rPtFToGkQJaUi7qS3QRmWH7a8/HyDQWHSKTo0i98a9sDEx2U5ZTjGUdTK+EhgFvWfuoSLVfcNQODLZqSJaCmIh/lW0ykCnXyzIdkAxSexfLuvEoGWYYyR5Svft0Mvxkeld2Q=,iv:5T8xc3KTxQiOejhbuLtE45RxT5ZuvxNNkTFmhgToMSA=,tag:BVanOHM2bbwF5DaZ45k11Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
