apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- pvc.yaml
- config.yaml
- cronjob.yaml
- status.yaml
- service.yaml
- s3.secret.yaml
- registry.secret.yaml
