apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satellite-data
  namespace: satellite-data-prod
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/olympus-app-backup: enabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-resilient
  resources:
    requests:
      storage: 5Gi
