apiVersion: v1
kind: Secret
metadata:
    name: satellite-data-r2
    namespace: satellite-data-prod
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:IPWb3C2gMVNfeyAHZTbY8FiHY7muU9vo3hsbDK/OuE1abdsrli24IRfhfbMGpSBZkWNB2x1rEfFZQ6M0Skt0D65e5Gj6Mqe0N1NpnhSzV50Eo2cMTaigtsKrHrB81s1XJTyPTijI5MTrtvClR5fwRxIQRDSKpWrVbKZnsSrMS41BV+mW69DMOLAf,iv:X3QzUCnYhWp2KBi6PnwqH3v3/UzyuzMTU+462+cPnO0=,tag:IXB4nZDWGwszpVJEpkMl9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcEZ1Sk1qZDc0N2tQcm1x
            OFk0Vis1SCtxVkZnbGppb2FFZnlNVnd5TFNzCnR4dm1SN3ZHZHRuVFhNWitoOXBM
            Qk5nUmdkdmducG9FeFJUM3o1dFRsUkUKLS0tIFNmcXhSb0lmblM0dHhKYVJRd21L
            ZitvK0VpSndldEg2SUhiUUIxczhmY2cKyniyn6NbOshkIvJ0U7oYAwNa8wJmXRWh
            IsXdKogozXZoW8wDSKx9R5B4/vAueK8wXmAQYS8bmbENzoknb2bIPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T22:20:13Z"
    mac: ENC[AES256_GCM,data:h50BtgwyonSNcSb1cwJFCKyChtbUCz+5/Q7pXepZKZtjLobFKOsWCTh8FI6BRroW45oRYA0mkQ/VK29m/uvkPS9gatilEyOV42YwexZhBGhAiFRsDGGDTE/kmP1Em2IgmVjzZK8/1RcE/CnhK2VtbwVIeOqjGcone5hc4QxFxiU=,iv:Ce/ez2o1PPo/RaX0iiHWA84E77WP6nVa7tTiW9wV0LY=,tag:aS4TqW5kchAtv5sozriTBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
