apiVersion: v1
kind: Secret
metadata:
    name: satellite-data-registry
    namespace: satellite-data-prod
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:tXZys6/lUQv4odSyYnaihp4fZaQl5YFH7Rld6TwB5QAOVDIwDZqaN4Xu/5oW8nqjjql1ao2lPRXRbOJc3vYWB51rdUon3DBv4d65yeYjsqrwV02U56IbwDNuJ60QrRXGfIFX665q3Jjn23P4tGrSHDivcVnK0CNi/PbSWh+cCu4reuBedV7vNOXjXcpWIkISDVq8AkdyOIy/4UJr6WSLzdu9Gqqhi+VgNI12QsjmaHfkGxNN9advcg==,iv:qyP0sjtXhSZk+TJL77SeZ320azWl5ua9w0rwGvTbe8k=,tag:QXb+E7RII3ARj8bbvavKxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUi9wRWorMUR0REc4UnNj
            V3NsN2x2L0kyTDRZR3hacEQ2MkZWVDF4emdjCnJDTjZSa2xjcTYybDNkV0RiVjZL
            QWtoSm9Rd2tSQkJ5SmtLUlFsZWNvMFEKLS0tIDhWMllvK3ZWU3V1anlFSXVqdXpI
            eHo3ZzVkRHFZRHJyakptcHlzYXNIZ3cK3ctLLiw7Tj9iWKaCHlJ2fJdrFcOvoqry
            FYelcx3NtpnshkSy3XOUn2qGO26Pk3aeKyWMhlDRlIziFJK8rzWIfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T05:58:40Z"
    mac: ENC[AES256_GCM,data:+doEVFWytq7k4ZoBI13egrOiEX9HYjNtTM/2Z6nKRDRXgLKhh5r3OnZUa4OJuyuw0dnmK0mlPGptgJoaPN9A7JU3jb5QdS11jFhLHJ7hllCm/RDbSxxfkzP5KPDLegW/ik2CSZ6noxyiJ4eDQxcuM3HK+bTf3aq7xZvzXwvQb6c=,iv:EdMd7QR7366lVgw2DpxGoTxl3V4aTIBhtt10UPTSoeE=,tag:39y0GBh9ZCrbRBHth1FZwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
