apiVersion: v1
kind: Secret
metadata:
    name: satellite-data-s3
    namespace: satellite-data-prod
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:nWaa+4I5JlJKx7sEBOa4JWxmksSNoDG4FzF9kqnblDHpXcWDVwGsud66iql1xHl0rw/1uEkKOlg0Vypmgw2AmXt88rZZ3pT3ThZ3tMZ9JW/ztsU2jUXoiBfCcoNC+4UNyV9Vwa7T,iv:HNWeSWhOt+YcgD5glKASOKQPD7UEngV17VClxgNP4jU=,tag:5140JrYBbXkZTmsKO66pAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Mm45QlZveXhmbk16amFp
            MWxtSFVlTzJvS0pSZVZhTEgzR3UrMGN4YUZvCm9Ub2ZrdWlkWldEQ21QQjF4K25z
            OTJGQXM0bFEvdzJQVGZrSElFUGV1SjQKLS0tIDVlcG9Iais1YjlQSmsrVW9HUWda
            MnRLK1MvN0JBRlR4NnB4bUVQbmVoUGsKU0b25/XWCBHLHsnYBl9CwycEQHXxJREZ
            /Q0T/eRW9tkD4ZmLsoy7DeQ4JVBeXrvMEcHKNxGtoJO3OFIxoqTVlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T05:57:11Z"
    mac: ENC[AES256_GCM,data:1buCr1u9gt3zs1vs4oi3z6WCDELqpNGRoafU4JmetU8NioVuV8G/7kju+fg8HV2B0dnrNqib/AG5u98wR8xuoyQiQhnbiDayM/Vnt1ZNcwW3vX9qROaurLbBA7GUD/UQNmuugkA+RwQgaUXhLM3kJObDrYLJlTj/4arHd5Ys7jg=,iv:dvlG4tvJ3yVp9DLlLGhJKw+boQShyG4pbaWkVGJImBk=,tag:WmKSPifnyyCo5lw3AoxIpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
