apiVersion: v1
kind: Secret
metadata:
    name: dubquick-secrets
    namespace: dubquick
type: Opaque
stringData:
    DUBQUICK_SESSION_SECRET: ENC[AES256_GCM,data:YhiZ2Q6ji81lgzfh6PoOUuTPOcYl4YKj8PZaOrHuHlA6recAT0wJlSdsAc4BI7eXoaM2b9zkUFrMxgcyhd1V7w==,iv:QDFNWXZnVxvDFgZaMjFlBelZMsXS8hAMtzxE/vQUhn4=,tag:hFhz0Glp8GWAUKWqwqg4UA==,type:str]
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:tvOBOb2OrQwWKsmvCBLhYKKDQmHYkc9ERiJ6mp6MmGM=,iv:OYPb7DoxTDJCbt5O6PdXpcayFB8vfb0uFpuAj0pnk4E=,tag:0AfuQOGUKdP8V1kH5clP1g==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:M4xI+msbOdmXLDgnTnQUM3OptIzGrRnJdtIYDAhQXuXYcAew9O3DYnKYthtnbb8a72mjyD6WGN78HGL0Gj7ZFQ==,iv:ERqCsA6bTMFAicWh817UUK7HiSTFlbu5ufEo3393YSY=,tag:sKIqOISYBidtCd10H7ZPqA==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:SxBo9JbMTprSoa+5vgetUPGY+FENxiheeCTufd9sqwh8MlDbf7E=,iv:EcBdPPrtEXfdlaqxcq7s8WT10cWJLKeyZopsKGyZquU=,tag:LLaoD6YXV9Y2+2j8ELOt/A==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:UDpohZjFpL/qHveiEwhTKWJ745iAKHf4kssSrmslLnjXCMmKaXKn8yHzTxhaCiewjUFeISG8fHfYagHEevhApWlHOiAPTF5Z39pc4bFYECb5Ne+DSuTuPlPbQryzHVaALY1GRNa1lDoFM7s=,iv:ntcyJLlbzhyJOIY7Vg0Y8fyHUfoYu7hm+0vZ00/vnjg=,tag:zSxOZQpZT2aunNRwb3jhCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNlpRSGlqdk5lZ2pCK1hr
            dFo5VmpIWWcreGJSN21BOWdZSmVwVDUvbkdVCmdNeGZkTjUxVCtpZkhvaEViVzRt
            TWN0WGF3WXJCS0h4dTEzSUp6QU9EZFUKLS0tIEkwSlZWUG9NMEE5ckVUbTlJVTFT
            S0FhTjdETFQyY2F0cVp6MXlNTzB1Y1kKwSUqJqzi+nIx469WjPgJ3X+rtWbKjvLj
            TeROYpCg4IM8grgNuFT7lp+i0Gnr5UMF7QAAwsnEuHiMSbxCBnNCiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T00:18:14Z"
    mac: ENC[AES256_GCM,data:KA98SwkFEm+d0EZwt6oCgiseB0ru7XZAHN/jboBgU9Hvu9TZ2ZQHnqBbjLKHKRCf63f95sQsnpatSoQ70Ft+UDMWjKYaDh1tGzEaLnNxCjOvcpONjbYffKG8DZnZRQXYnfriixvfmHFq6uCOhmYEcntlGBtO8dP+MTLzPNbZvZo=,iv:9MSsuKjUYJp+IxomSQqGc6IyD8R+qDAUqwYUrz0q/gg=,tag:lFrRf3hxJYb15FQQbtX9Pg==,type:str]
    version: 3.13.3
