apiVersion: v1
kind: Secret
metadata:
    name: dubquick-secrets
    namespace: dubquick
stringData:
    DUBQUICK_SESSION_SECRET: ENC[AES256_GCM,data:3kMAWRRj6og2qgMAtbhKRE8ZNexDaamTXf1rra9XnGRGw+Azut5sST/07HJnd+LRpKgz6O+jVJ67+bSFwsiRQw==,iv:GnUUc+mGDWXg//mwUf0GbxBhllsksmRaN1JiBMWfEu4=,tag:D/LaoiejOGfpKfbWIzEzwA==,type:str]
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:gGUNWGo0SqWHCSBomketOfJ2LmaQyCyS5Ryk/jx/J+Q=,iv:SKyJWuHVC8CPwonkZmYChZeqYqZeOdAyV5s3vJhbyZM=,tag:X8LPC6YYl7Dc3E/g+zPDLA==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JfdoqK8Tu+EHa2dksIx4rnyS+7PQoYmxDzCKhKocZ71FyEwkn8GBJ6BkScxelPIYrfPJZ8Obhdsv5iG8bWaXkA==,iv:7QsHAN2LfzXA/tpmhKmupWSZo9y1V0QBqCS+Kx09pMQ=,tag:art6N8onQFYViyZFgJm4pQ==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:2Jd5WZpeGfmHecKnRoQ0yYWXh1ZK8D8jU4cDIbqw8A4hDNh/ZrDTdVLlnAAki5KDUUWewKOa4mIi17zgH4Kznszw0bThT7W49Wq0Ok+6fIeJifbIQNv5QbFCE6/1y1uEEAcgp+pAKo1Acrc=,iv:1d1JTpA87SjQCtuRokXCU/o2cUdjf3rtRE4Kx8vVmgc=,tag:5JP4jIp/Dfos/rvORPYv4g==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:EBNs1a7X5sUqG0oAfxbLjtZvVanfdwYuKmjx9L0kmMPPcLyz+k4=,iv:/q01yCgEmZ+YjvDexNC66upvKpKJD/VVezuyxoYuPCM=,tag:EA9TxhlQcTjvCQtYBPXp1w==,type:str]
    MODAL_TOKEN_ID: ENC[AES256_GCM,data:07HS2Er6x4QGyjBOmMUlb8I3Ap4C+4Sq7w==,iv:lZzbQQtLHm0jWlJoOpLqRP6rkhZbhNFzoFntSySkANI=,tag:Cwn0JtkNEVuo3pHQqvOQIA==,type:str]
    MODAL_TOKEN_SECRET: ENC[AES256_GCM,data:7CMMMWPQlYxIFa3bwyXJQ2RlSYvXyHCImw==,iv:HwDq1U4G6EqC0IARfY8rOuOXptHJBk6jE4ThVwXlpVQ=,tag:Dc71V8bI8cmln5N5OEgUnw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2emFtMU1LWHVLZVFRV2Mz
            UkVzZXRUWTdaQjBGUFhKd21FTkhxK1BpWFhzCll0TnlSUzU4TjNpdk5LcGFyL0tr
            YUVCTVphWWhOTnprK2VMUUM5WWNJZVUKLS0tIG1OUVpkQ0hlL1J2VG1zNHQwMFF4
            YnhMVDB4ZEozWnY2eVI5V05sdkdlTGMKNHI2jTFmY9VZvnHGyXHvMGj4yk/UcPCd
            AO8OMcjopNX8BY155SRpHrYuneY/HUHysH+MuwgLD8VaL0C1jyrXXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T01:59:24Z"
    mac: ENC[AES256_GCM,data:WfFw8visowJeFNVHautI+f7L75NDQmnDm4h+h7Pi4yw4YzlmuJ91nLdibSf6d26yHqObklInzxZrrQJYMglADtEXniPmORYc2/QbX5vlj4uaijfFE9/O70hOr5+DkJ/YIrCqdJS8svU1iqIgNeHF6gsHOUxH++526sUYBZP+KbU=,iv:ujVH/sA+DmkuWYw0PNwtPuXDCnGmlJwueqsgjMreIx4=,tag:M4BwDniBUXY/+T4Kk7psSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
