apiVersion: v1
kind: Secret
metadata:
    name: dubquick-registry
    namespace: dubquick
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:VegoCUVKIfBmK4/5fWQI72XvdJh95/NjEmOLVO2a2CtuY4hxU271YgrQ1P9M8JnBDA0b4ekvBBKISyZVljduOzOTgOfxquutXMhmNd0plnOvNjJmFP2+Qgnq8cESBuBy1CNrfa92Jx0=,iv:DlSiObIHmE1vL1BLqVZpwf01iUgmmJzIdNejxJ3ajWQ=,tag:V8rYsGUwjDiHa0vIgDXwwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRGw2V3pTdFQwVGxBSHJG
            SDNHM1B6YUlZNzJSWE1GVWdodkswKyszMHhzCjBLTkl2SXpWQUdNZ0xZN2RldmZw
            d2h2THA3RHY0SXF0ekxURld1eXZlbU0KLS0tIE9CTXJ0UjRGZzJuTWxqVHRGbW9K
            RGRoNC9ENFk4NjdiWHJLcUNRNktkVGMKEqZa281oD5L1apXWKHI3Ih1d35dhOwNE
            5N29FB+686pTrV2it1HZ3eDLzcDCe7imuCfDjN2hGB+GSDjBjZmkdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T00:01:03Z"
    mac: ENC[AES256_GCM,data:qHIL0i+aTC+Ns8IjCZkE3ysfAHAQdMxwuxnV29641mUEjpH/9/a+XxHFjNBhnH6ZyKVAyx0Qg1PiWCKSAcdFr0V10Uvg0az5G383ebyxeYdTIy8Ar02R6U5Y3yxQxOXBe4ONEjw1aUu8hUQOCG1Q+zVHN2iH01rg/oqmejJRj60=,iv:FWaDFJPAlUJ+hWaR+8UkcxY+6Xzwr6POFwrB84BDk2g=,tag:CC86JHnCsmbT4hnySnHTtw==,type:str]
    version: 3.13.3
