apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dubquick-state
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/olympus-app-backup: enabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-resilient
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dubquick-scratch
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-bulk
  resources:
    requests:
      storage: 30Gi
