apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:t379f2fV7ovN4Y9mVZYQ014uWiGyAekWcBoaKy8AUxpsAYRs3BCj98ujF/6HEVdQr0iyHzgGwBMdA80z909p0kg2ka887oZelumMbkVXLPwLqP6hwlU=,iv:AGipQsvIQGkf3VOwIjdvLR3PATEG8IKqc/6giYxiIn8=,tag:Qnq/4784ybJlN9F7vIPXrg==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:SrMd/uTvScNt/WcrWpp25WO/,iv:FIGPlFxYpvGlYt0SgLfiAE/71ILfrPIbrQB+diZUfa8=,tag:65wWkBbMKhHSYyCPtTVaTw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:vjm1rGA9UhLC,iv:7POS/VReE8byCo0J73IOwNO36KVUi577wM+X4GYo7ns=,tag:ckPLkhwacGMqzYoMolVBmg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:0+2c3gu30Jap,iv:XGGT9rYgRuKO2xLKFl0VbVPznYEzzwUvnoLBFh3NdQQ=,tag:jg6L2Z++JmAWUeEz5+nsxA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:JlcWzSJ+VCplL6FP31oVlzqybA0L3SyRWdnEs/xghaHC2NjQ+zMrhYn8QeL59sqB,iv:oQL2bjKpuJNX5BXSov9iqvOFCiCI545MAEpXzAPYoGM=,tag:/7Zqb1EuzdjHKh2bo0N8ww==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:fBZxp+Vz5OxSdmPiwCks45AEHUMadcv7ZUUGuSKkqEI=,iv:uXzfg0C7+dS6WSJx7TtxZfxdvY+EKa1Ba5XQ5W2urFw=,tag:EtdxaEMTcj0GTYrLPqKf7g==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:8gzsAgf0I+GoS3IxImUCUm4sg5Lb6BJ4+pfzmJFTT9mBBEVJtjm8dyzVs8s1v/RX/gIHMxb3k0kIxSyMTCqCPQ==,iv:kaSDysgcmZWi7OEhZbZabjb6q57eu62gpTNbM+qaXoY=,tag:0ZwQ7lWK1pN5r2aHKlvkow==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:sN0gxG+m/51NeWA+VAhfliAe7gc=,iv:S4e9/JgaJRtQKoqTjZq+sAwTVP3aSmErVLYDp1sOQJQ=,tag:JwZcB2ng5WxHKFBHATwgxg==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:Lk3vNfU=,iv:kKgkG5diDvCRB1RhsGppDlYRJzbh/J5FIQcpR+jgipQ=,tag:W8b+Uuyu07f0AWRCK7T4HQ==,type:str]
    AUTHENTIK_DISABLE_UPDATE_CHECK: ENC[AES256_GCM,data:4Iqtxw==,iv:ELMJRym9c1PiI+iEWUC4+WQgq5XtGfn9RP6h31jILXc=,tag:oxb6tkhD1xGkSlQXauhwRw==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:lAqX5/9W6c1bUXWUABKYF67tJDvZd5xwXeoclsCG,iv:nUhDbD30WUTny04x0qgJn+VKFIB9GszCbUjHNpft7w8=,tag:yTqsmZXh4jgn/PhxYyY48g==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ibrc7q9WCr4V+MyTAB/i41HZ/TpoucyFXKRT8qpPy6SlNOXBuATxUREF77gKJ10/vP6vGBzmE/NKFhGE7DJ+bQ==,iv:/t//RSzS8V88zr/US1GPsJKSjQgEdn9cAQVctV47HLU=,tag:iVaOosrYNbecS5m41t+OZA==,type:str]
    GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:8zEDHv6P1OJf6SbXtyd2UKugUXIzetxnJ2yjhm4XY2nSdk98iPrgMHTokP1W8x7Ww2O2+FgfSVCkcpxlLk8AN2faVLFmMxLb,iv:YFdUwaJ8aHcihEAw5ICFyqx0hjZthJeAfCxH7LXWe9I=,tag:0q2c1WSLk6gTT5GG3jC7jA==,type:str]
    GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cXpZ3diS/CH3nhfQrOx4RJixYg3wcGV2bRGfEgZh5fJcD6Y=,iv:XIwQ+gyQIiqizsfTjnvUkCAGoTVuJDqUe+Vj2dC8Eb4=,tag:y/+zI50RWOa5DYxw4u/uiw==,type:str]
    NETBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:meEGl/AxiFhYBzI9MEA=,iv:GHaB6TQmpQc9ylydBbQhy0YRpPKw0xQ3uSCTUWYji/c=,tag:IrtLxLNUmRK9KSoFy8U6qg==,type:str]
    NETBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:PHyhlWBiNA0Ofi/KjLe4l/U0It6Ba2YNZ+p8pZFn5e0fFNp2qVw0UISFWH1+Zz/xmkj6h5LWRv2bBOXmc+7I7A==,iv:4Hz+Qq7aMpl/htrzyPpklyh4ABn1ZOgEKDBRnx92Z5I=,tag:1qSsMLwft+YrZ57KiYLraA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYmZqeVdRN1VjemtQRzE5
            M0pQT0RzT1FQRDRNM2FkVU5ieGM4Mk9XSEJJCm9OcVl4RE9QdytWYzBWNStXcFNv
            RjVVa002cCszUWZSQ010d1ZYejRmUlkKLS0tIHYxaGNFRVBoTEswNWZjV0RQSVV4
            ZEFkdEovZzNwQ3Z2L0dKTU80NUFtakUKK6GOdBEjU8JCl3mjsMFtDOVE/9XkwWxb
            /+ATxZNrYI8/iphSjcRhNC62otjGJTVHQ1fq8DALrPHsGDsF85ejpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T02:20:04Z"
    mac: ENC[AES256_GCM,data:GU5S/1NKUCcV4lii8Xd9si9OP3pKN3Mp1iCgufBjXUsl2J6F0hJnXx/vaRLaNDc+WWPQfF/SECcB61gS/z5Z/96KtXWnmdTuHvg39ezS6N+ZrukJsPZRlc5TxdYJH1Ihsyw/9WTgVNb+BTT16Cg2fdCAxBSlsHokJvSwfuFwbjs=,iv:5gm9jMHQgBh4ATalPJtD3HrrLZlDwT0VpvJiE9Ecp20=,tag:eq768uS3QAjdBOwH1EvlUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
