apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:bFCZ/OSl7z2IPhOReUhlYVqy0Pp68738326uDx+aG5vcdro7mf0tUvrb/q+gStM6tNg8E/+Oi2b+zBerGdYaPByOrmSEojc0NIsUpDgpLd61683+IOw=,iv:MB9p1Fbhk6KW5qYZGUFnnyne7cDqKfj6DMki+8N006I=,tag:kW+jX+QvjyK4AVavlKgNQQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:8EtQzM5XhwYIkKQdpNYyIN9a,iv:oWq3BqFDc/BWkYBNR78CSlyYcS+LMF8PKCdPa9GxVJs=,tag:7pK1yG1yUcJHbHArLKVZ0g==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:oYKVWL2l0iau,iv:D4mxLV/OY12bNQQg+5opfUn9370MDqczc0hg0B1PrcE=,tag:QG15eK+xICt77OMQvvOnlQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:azgUKqI8BEVi,iv:T/4I+M9wkO8bdarcAKGp1yQ6LH61Flq4vQA4+qnOWB0=,tag:4zcfTUEy+Fc3iKqxmeUaag==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:jhdT7YWCTKD7JhAygP9KpmQX39yEC5+Ay5d5o9Lk+w2WE0vCz4CHQFtW3o8uA6TH,iv:wyG/z2MQZJ69o5pTjHeY8FgncA5yaMFIpkM9CuMCPBI=,tag:Bvi2vGlXtkBajn3UqIxCfA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:widjTHK1gN5CKg7UdiAGZyTPKVsnyEx9M40xdW7LgVk=,iv:RAYNt/NbjrxizlQGgxyoDpQ/9EAc8/2lh+5rS7M1kHQ=,tag:lQzNi9odBOrB5TerlJRJpg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:cmCb9mMFnnWcW0wPpWeLCvxHcJFsTO/Fqf7s5j7Wv5T2YTXdfFg4vsv8Sq4nCD+amPgTw0+c0PbaCNDBINhQug==,iv:Mew4wEydEX2+84IDeW+DBLtzCUzvHBrRmHPxWeJzmPU=,tag:d8oI0rbhnWcOv+OLHDvXmA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:bC/YDkPh2EX1d9gmSnM4ZLq4a78=,iv:3CwC/BtEFAXBYBC0LCssaF9OHlMafpi213aF5cwS878=,tag:zOGGR6tXRsQAdCPBcfzSRw==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:dKCHhOw=,iv:J/J5D1SDWFSu/sC6dfZ9VtGV8HwvNheEF4VDKsAapjI=,tag:w0oacSWptf2kuACKC8C0lA==,type:str]
    AUTHENTIK_DISABLE_UPDATE_CHECK: ENC[AES256_GCM,data:wfatNQ==,iv:XpZUsftvtXG/C3m53SIrWS6OwU5XbzmJnzbw4fLSOu8=,tag:nnmTi3dJ50sI7bwbm3lWxw==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:UiRJXB9XRc/CTJXN6n8BIXEqBJjLMgkiFfFELnMG,iv:iPCOwzhm0aNAWoEz6EKgMu55m3C0g8ANoJ6U0e2MOtk=,tag:qJNeVwqsh5i87uINwt8M1A==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:yV4z98lw5uSUpoqzdgkyoaUfQG2XkycJXT670NmzdAUX1f7WIMqo8G0Da/Q7LyIyUSlMr5hTke0ONDtDEMETWw==,iv:qF8Z36TId7EGbAEOLoA3sKSZO42kzU6LNdqJOONyCTY=,tag:e9hSp/Z9cLKp1Dx20FsxJQ==,type:str]
    GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:XxcGxk6mLGjHBIj7PjAXBpqP7zqwpxith6t2/8A5EAvE71JjzIHdLeTO+pObivKOmMt5mqsJtksc+FfSqwUXFoPGgv0Gv3bF,iv:c048bww+vUZFOg7ESlcLqHgaqjJAIzPh/NQn5UM9rqE=,tag:Mm4+f8rooeyndRZ87BCLwg==,type:str]
    GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7AIwjBwHbBsZwUhHfiqW6NRPS3oPbWSZmPAWNtHf5gT44WE=,iv:3SaJSk2aBPapjvHVUvVX5WxmNUu87T4TxNoJItxFoL0=,tag:PQbICJuOhBF5xQMrSkn2FQ==,type:str]
    NETBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:LLmDkrhb4PNpe5asvsg=,iv:6DwzOHqolPMT7xBoPhJzNwipTAyuLP6b3VhtDg2HVcU=,tag:CkCthf3+rimgmYE0INo7WA==,type:str]
    NETBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:t7JTv50LmcbuK6k6FRyCVli6XM0ExVbov5zUfcdX8blUgDSokYpYjLfmC7ZRQXHlt/HCpsNIruEqnjY6eu313A==,iv:a+CBJshyKRUpOMn4jLSW6mS1xkDbrpOoldKqSyK9RUE=,tag:lQ1rNYheR2EBivx4xD9M0g==,type:str]
    COSMOTRAK_OIDC_CLIENT_ID: ENC[AES256_GCM,data:AtLWweTzL67xunw6W3SuFQTZU3+2EG8=,iv:Gitm/yNoF3vC/pg67UJN66TYmdpoBzoyhaK+CNw/jNw=,tag:ubw0kXGFrhL4uxW1EIcyHA==,type:str]
    COSMOTRAK_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:cP9jZPuPI9DOUh1gfjK6OkEfZ3mc6tFsMjQLfOLMWDM8UGXxVEvv7opIB70az3/SJb/RKqiP08L5demWXljkpw==,iv:z7oVQ+ZwYIqChJN7mExzAh/iCs9YN+fUtRAlxJXdSQ8=,tag:5KVIN3Et8ntuHwgU3jU/5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcFFrSWNCUjhRUHAzWXIx
            QlY4ZmRtekUzVzU3OHB3Mis3eldrZGRpaGxZCnpSMXZJeGFKc29FdDFIZEd5clkz
            M0tYMlBVdkJGaE1CZHVnUjl4TmZwd1EKLS0tIEdPOEVSNjI2dGtXRHlKVmtseFl5
            TWEwVXAycnhlNnl4V1hEMjJiN29POFEKcHA/eVFxJH/YCzPP1+ITvPgJOJkBpHaD
            93Z4zV8Q6hQgs0IUPsJDdxKFfrejr4TUKoX3ew8ENSM9BrvdVkc2Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T06:03:20Z"
    mac: ENC[AES256_GCM,data:CBIJ6NZCUhdoMoR92uuAGFkW6FAadar2S64dOpI/e6pOaVZ8FxZIxqskd/qnrcpHYaefQhnfBQ39z0hYVjmeyF86UTBohaGyClsJ0cttfp+0uCN+Gz4mORnmRI+3yo1/h2EYfxRFPq3lD9p14DR4t9VXDVPvGZpcQUUnd0B+I5w=,iv:s0CKCPuasJlxfUQ73DwZwEscDV5v/lzexmE+TNVL8dg=,tag:A8Ux+uqrYKltRALM4HfXmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
