apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: authentik
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:nigVfEKjJADR2V9A9v68vWZg+4jR/hmJhJlRzuBRGP+E5DP//eHXJVDTlin7Zbdm7T9NpEmrojqjlcPBNUxaOYKi0Ma0o3BoihxGzg0W0dz+mpGegkrNKdbYAR2dPP+74E+tcP4kYMUyYohffDFDKQCzYwoXyvs4heOoekKkbKeU936HUz+7pAMUIY8mIOJ7cSFi+Z8PmeLapugX+ij8cZQ6epWzfp+Rg2v/0JyzAZSfYeSQCn36yQ==,iv:wu/32/ITqelQrElJQPsnHklB9jpS3o/DG9iD4nf29EI=,tag:c65m26cbra4cos1rqmFMLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1489u3rqf9c0e4tkah0h50n2ktnkjszlezrvpvkhmvz5y80n7r3fs4dhfcp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMW1sbjR3WGMxVHBlU0Q0
            R25uZzU4UEFScDJWUXRsa3c4RHpKWlVIRjIwCk1JSXZuOTNGempDRUV6QWNqVkd4
            OWtVWlIxeDdBMnBjeGJpRTJLNEorancKLS0tIC9pSkJDajZxbFUwYWMxYjg0MDVo
            NVg2bC95cEJ1ZUVPcUZ4SkV0bjZDa0EKAKuoyP2nKdJCLoTxhfoXwFcnl0jBB6JJ
            NB6iKhRLNWyn07PYGuRCUzG2on7Y0GHa1xln3Hk7UAbVbCSqyVbxaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T06:53:23Z"
    mac: ENC[AES256_GCM,data:vdPbDrNk4+RcuBGKgWrisNRCf4+jgE0SR10fZfM4OKKuaQuaV+JhxW+eJ4K6GKIaCv0wpBHUXs6wEXgT8702WJoE8GS94OiT7+4+FLlp0exAUrKg5SsiQxHdkPOiaeGuFUFQTtOYYS0+OtqZTxwkbk4JgEzs5Cas4+e1C2Z+Hjg=,iv:0xloTmPjRTrBMW2g5a4k7xvqU+ZEWE8kmAqZu7z/uBM=,tag:R95fXw1Q+Fn3oyj/UtkGFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
