apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: headlamp
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: headlamp-admin
    namespace: headlamp
---
apiVersion: v1
kind: Service
metadata:
  name: headlamp-tailscale
  namespace: headlamp
  annotations:
    tailscale.com/hostname: olympus-headlamp
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/name: headlamp
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
